.travis/custom_release.sh
config/webpack.common.js
package.json

Sorry man, I should have caught these yesterday :(

Moar deployment fixes

---

src/Api.js
src/Components/EmptyState.js
src/SmartComponents/SamplePage/SamplePage.js

Add initial pre-flight check for authorized users.

---

src/Components/EmptyState.js

Updating docs URL per https://github.com/ansible/product-docs/pull/856#issuecomment-532976864,

Update docs url.

---

src/Charts/GroupedBarChart.js
src/Charts/PieChart.js
src/Containers/Analytics.js
src/Utilities/Legend.js

Set height values for our Legend component in order to handle numerous orgs displaying on the page.

Add overflow to chart legend component.

---

src/Utilities/Legend.js

Related https://github.com/RedHatInsights/tower-analytics-backend/issues/52

Adjust Legend component for better handling of long titles.

---

src/Components/ModulesList.js
src/Components/NotificationsList.js
src/Components/TemplatesList.js
src/Containers/Clusters/Clusters.js

- Set max height for Modules, Templates, and Notifications lists with overflow.
- Pass all notifications received from API to Notifications Component.
Related: https://github.com/RedHatInsights/tower-analytics-backend/issues/28

Refactor to allow all notifications:

---

src/Charts/BarChart.js
src/Charts/GroupedBarChart.js
src/Charts/LineChart.js
src/Charts/PieChart.js

A small PR to clean up some dead code.

Minor Cleanup

---

src/Containers/Clusters/Clusters.js

Related: https://bugzilla.redhat.com/show_bug.cgi?id=1779927

Fix duplicate entries being apptended to clusterOptions array.

---

src/Api.js
src/Charts/LineChart.js
src/Containers/Clusters/Clusters.js

- Use `useReducer` to update queryParams object.
- Use `useEffect` to handle queryParam changes (e.g. fetch new data with updated parameters).
- Update Api.js to pass in params for `chart30, modules, templates, and notifications` endpoints.
- Update LineChart.js to offload data-fetching to it's parent component.
Before:

Implement top-level filters for Clusters view.

---

src/Components/TemplatesList.js
src/Utilities/helpers.js

Related: https://github.com/RedHatInsights/tower-analytics-backend/issues/73
https://github.com/RedHatInsights/tower-analytics-backend/pull/150
- Add success rate
- Add number of total runs
- Add name of top failed task
- Add fail rate
- Add job id
- Add template type

Enhance top templates modal

---

src/Components/NotificationsList.js

Related: https://github.com/RedHatInsights/tower-analytics-backend/issues/7
This PR adds a linkout icon to the tower instance from the Notifications panel.
Note API changes are forthcoming in a separate PR.

Linkout notifications panel

---

src/Api.js
src/Components/TemplatesList.js
src/Containers/Clusters/Clusters.js

Related: #68 
Sample request url now includes queryParams:
`/template_jobs/21/?startDate=2020-01-11&endDate=2020-02-11&id=88550`

Add queryParams to requests to `template_jobs/id` endpoint.

---

src/Components/TemplatesList.js
src/Containers/Clusters/Clusters.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js

Call insights.chrome.auth.getUser() before each API request.

---

src/Components/NotificationsList.js

Conditionally render linkout icon for Notifications Panel

---

config/dev.webpack.config.js
config/overrides.config.js
config/prod.webpack.config.js

Add hash to webpack chunkNames.

---

.dockerignore
.travis.yml
Dockerfile
docker_push
package.json
src/Charts/BaseChart.js
src/Components/TemplatesList.js

Adds a docker build for the front end. This is used in the back end development environment to provide a fully working system from one repo.

Adds docker build

---

package-lock.json
package.json
src/Charts/BarChart.js
src/Components/ModulesList.js
src/Components/NotificationsList.js
src/Components/NotificationsList.test.js
src/Components/TemplatesList.js
src/Containers/Clusters/Clusters.js
src/Containers/Notifications/Notifications.js
src/Routes.js
src/Utilities/helpers.js
src/Utilities/useQueryParams.js
src/paths.js

Related: https://github.com/RedHatInsights/tower-analytics-backend/issues/70
Depends on: https://github.com/RedHatInsights/tower-analytics-backend/issues/66
- We will need a Top Workflows panel to replace the Notifications panel in the Clusters view.
Backend ticket: https://github.com/RedHatInsights/tower-analytics-backend/pull/225
This PR creates a dedicated notification view with the following:
Sort by Cluster ID
Sort by Severity
Sort by Date Range
Pagination

Breakout notifications feature

---

src/Components/EmptyState.js
src/Containers/Clusters/Clusters.js
src/Containers/Notifications/Notifications.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js

This PR handles the request to remove the white background from a full page EmptyState component render. The copy for no data empty state has been sentence cased and period removed. A WrenchIcon now replaces the CubeIcon.
** Linked to this PR:#95. The branch had to be renamed due to a Travis CI build error.

Empty state styling

---

src/Containers/Notifications/Notifications.js

Removes date filter for notifications since it is not implemented on the API

Removes date filter for notifications

---

src/Charts/ROITopTemplates.js

Fix X axis label error when dataset is empty

---

src/Containers/AutomationCalculator/AutomationCalculator.js

Related https://github.com/RedHatInsights/tower-analytics-backend/issues/345

Update copy on top template card to be more specific

---

src/Containers/AutomationCalculator/AutomationCalculator.js

Linked issue: https://github.com/RedHatInsights/tower-analytics-frontend/issues/131
This PR handles allowing inputs to take decimals and expose an error to the user if a negative value is entered.

Allow inputs to accept decimals and error on entry of negative value

---

.travis.yml

separate build and push and disable push until integration is done

---

src/Charts/PieChart.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js

annotate piechart org success

---

src/Containers/AutomationCalculator/AutomationCalculator.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js

Use sentence casing in card titles

---

src/App.js

Fixes https://github.com/RedHatInsights/tower-analytics-frontend/issues/48
https://stackoverflow.com/questions/45978230/get-version-number-from-package-json-in-react-redux-create-react-app

Add a top level hidden div with the application version

---

src/Charts/PieChart.js
src/Charts/PieChart.test.js

addresses https://github.com/RedHatInsights/tower-analytics-frontend/issues/75

refactor piechart tooltip to understand the data shape

---

package-lock.json
package.json

This PR handles bringing in the stable release of the crc FE components package for version 2.1.0

Use stable release of redhat-cloud-services/frontend-components package

---

src/Components/TemplatesList.js

Fixes https://github.com/RedHatInsights/tower-analytics-frontend/issues/77

disable borders on template list and add last N jobs header

---

src/Containers/AutomationCalculator/AutomationCalculator.js

fix jsx-curly-spacing linting errors

---

src/Containers/JobExplorer/JobExplorer.js

Pagination max display limit is reduced to 25 to match API limit

---

src/Containers/AutomationCalculator/AutomationCalculator.js

Addresses https://github.com/RedHatInsights/tower-analytics-frontend/issues/189

force calculator height to 100%

---

src/Components/Toolbar.js

Quicfix: No default value to date picker causing errors fixed

---

src/Components/Toolbar.js
src/Containers/JobExplorer/JobExplorer.js
src/Utilities/formatQueryStrings.js
src/Utilities/formatQueryStrings.test.js
src/Utilities/useQueryParams.js

Sort by filter - array to single select

---

src/Components/ApiErrorState.js
src/Components/ApiErrorState.test.js
src/Containers/JobExplorer/JobExplorer.js

Catch api call errors and display the message nicely

---

src/Utilities/useQueryParams.js

Format dates as UTC to address timezones.

---

src/Charts/LineChart.js
src/Containers/Clusters/Clusters.js

Add cluster_id to properly filter jobs from Line Chart.

---

src/Containers/JobExplorer/JobExplorer.js
src/Utilities/constants.js

Add default filters for job explorer.

---

src/Components/TemplatesList.js
src/Containers/Clusters/Clusters.js

Fix: Add cluster id to the query from templates to job expoler

---

src/Containers/AutomationCalculator/AutomationCalculator.js

https://github.com/RedHatInsights/tower-analytics-frontend/issues/183
**Before**
**After**
**After clicking on one:**

Feature: Add link from ROI calculator to job expoler for templates

---

src/Api.js

Addresses:
https://github.com/RedHatInsights/tower-analytics-frontend/issues/200
https://github.com/RedHatInsights/tower-analytics-frontend/issues/199
Tested against prod.foo.redhat.com non-local backend

Templatize the api version and start with v0

---

src/App.js
src/App.test.js

Just a tiny bit refactor. No changes, I swear!
Since react update in #182 console gives a warning about upcoming deprecation. This commit fixes it with converting App.js to functional component (and throwing out unnecessary lines - talked about it while tried to fix a bug with @ryelo )
@benthomasson @kialam Maybe one of you can review it? 
Fixes #250

Convert App component to functional to get rid of warning

---

src/Containers/AutomationCalculator/AutomationCalculator.js
src/Containers/Clusters/Clusters.js

Fixes https://github.com/RedHatInsights/tower-analytics-frontend/issues/160#issuecomment-690584475

catch rejected promises

---

src/Components/Toolbar.js
src/Containers/JobExplorer/JobExplorer.js

#186 
Could not find the exact cause of the problem, but checking with type for true solved it. The values passed to the component are seem like always correct.

Quickfix 2.0 - switch default false on job explorer page 

---

src/Components/TemplatesList.js
src/Components/TemplatesList.test.js
src/Utilities/helpers.js
src/Utilities/helpers.test.js

allow formatPercentage to handle zeros

---

src/Api.js

Add offset as a pagination param to job explorer API GET request.

---

src/Utilities/helpers.js

Fixes #227 
@Ladas @appuk 
Wondering if this change fixes the timezone off by one day issue - can you test this locally before I make the rest of the changes?
Basically we are currently converting UTC formatted date from API to local, and _then_ back to UTC, so causing an off by one day bug in the UI I think. This PR fixes the format ordering.

Fix 227 timezone discrepancy

---

package-lock.json
package.json

This PR adds the PF React Charts library to the AA project repo.

Add PF Charts to AA

---

.travis/custom_release.sh

Adds custom_release to push devel to ci-beta

---

package-lock.json
src/Charts/GroupedBarChart.js
src/Components/JobExplorerList.js
src/Components/TemplatesList.js

Reverts RedHatInsights/tower-analytics-frontend#288

Revert "Fix Misalignment in rows with long Cluster names"

---

src/Charts/BarChart.js
src/Charts/GroupedBarChart.js
src/Charts/LineChart.js

Change D3 `timeParse` method out for `utcParse`.

---

src/Charts/BarChart.js
src/Charts/GroupedBarChart.js
src/Charts/LineChart.js

Reverts RedHatInsights/tower-analytics-frontend#309
Dates in charts are now ahead by 1 day ([see comment](url)).

Revert "Change D3 `timeParse` method out for `utcParse`."

---

src/Utilities/helpers.js
src/Utilities/helpers.test.js

fixes https://github.com/RedHatInsights/tower-analytics-frontend/issues/316

add full coverage to helpers.js

---

src/Components/ModulesList.js
src/Components/TemplatesList.js
src/Containers/AutomationCalculator/AutomationCalculator.js
src/Containers/Clusters/Clusters.js
src/Containers/JobExplorer/JobExplorer.js
src/Containers/Notifications/Notifications.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js

This PR handles two UXD audit changes:
**Change badges to numbers (#272)**
Current:
Verification:
**Remove Automation Analytics from Page Titles(#275)**
Current:
Verification:

Misc UXD Audit Changes

---

config/setupTests.js
src/App.js
src/Containers/AutomationCalculator/AutomationCalculator.js
src/Containers/AutomationCalculator/AutomationCalculator.test.js
src/Containers/Clusters/Clusters.js
src/Containers/JobExplorer/JobExplorer.js
src/Containers/Notifications/Notifications.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js

@kialam I think it solves the bookmarking described here: https://github.com/RedHatInsights/tower-analytics-frontend/issues/128.
Right now solves the `bookmarking` issue and the issue with the back button.
* The bookmarking works as expected
* The back button works and takes back to a previous page (ignoring filter changes now)
* The issue https://github.com/RedHatInsights/tower-analytics-frontend/issues/80#issuecomment-681088367 is still present.
Demonstration:

Fixing back button and bookmarking

---

src/Components/Toolbar/Toolbar.js
src/Containers/JobExplorer/JobExplorer.js

Toolbar fixes

---

src/Containers/Notifications/Notifications.js
src/Containers/Notifications/Notifications.test.js

**Additional fixes**
* Notification page paginations fixed (the same issue as on JobExplorer - the dropdown dropped in the wrong direction)
**Tests**:
* Not containing API Error testing (there is none with v0 API on the page)
* Toolbar not tested, probably will change to the unified toolbar in the close future

Notification page testing

---

cypress.json
cypress/integration/automation-analytics.js
cypress/integration/common.js
package-lock.json
package.json

fixes video recording issue https://github.com/cypress-io/cypress/issues/9265
hopefully makes notifications test more stable.

cypress: bump cypress and stabilize notifications test

---

src/Components/NotificationsList.js
src/Utilities/useQueryParams.js

This PR fixes the following bugs: 
- Timestamp for Error notifications appear encoded and are not human-readable (AA-239: https://issues.redhat.com/browse/AA-239)
- Timestamp not displayed for filtered notification items (AA-246: https://issues.redhat.com/browse/AA-246)
- Some stringified timestamps show negative integer 
**Before:**
**After:**

Error notification/ filtered notification item timestamps

---

src/Api.js
src/Charts/GroupedBarChart.js
src/Charts/PieChart.js
src/Charts/PieChart.test.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js
src/Containers/OrganizationStatistics/OrganizationStatistics.test.js
src/Utilities/constants.js

#240 
Fix for negative values: https://issues.redhat.com/browse/AA-131
@Ladas

Org dashboards update

---

src/Charts/GroupedBarChart.js
src/Charts/PieChart.js
src/Utilities/Legend.js

Working switches:
I also refactored the two components while trying to debug to functional components with the following process: 
* `method => arrow function`
* `state => useState`
* `onMount/onUnmount => useEffect(() => {}, []);`
It made easier to debug as we are usually much more familiar with functional components.

Add switch to pie chart legend

---

src/Components/Toolbar/ToolbarFilterItem.js

Add filtering to the toolbar multiselect box

---

src/Containers/AutomationCalculator/AutomationCalculator.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js

Move filter toolbar to the top title section per UXD's suggestion.

---

src/Api.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js

related: https://issues.redhat.com/browse/AA-399

Remove sort dropdown options; hardcode sorting for org stats page.

---

package-lock.json
src/store/index.js

After upgrading the packages I forget to update this line. It was working since I did not regenerate the whole package-lock.json just updated it. If you do a fresh install (remove node_modules and package-lock) it won't compile anymore. This PR fixes that issue.

Fixed the wrong import in the store causing not compile

---

src/Containers/OrganizationStatistics/OrganizationStatistics.js

https://issues.redhat.com/browse/AA-166

Added query params to the bar chart redirect

---

src/Charts/GroupedBarChart/GroupedBarChart.js
src/Charts/PieChart.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js
src/Utilities/Legend.js

* Fixes the issue with toggling different chart then is next to the legend.
* Fixes displaying empty string in the legend instead of the "No organization".

Fixing org page - AA-481

---

src/Containers/Clusters/Clusters.test.js
src/Containers/SavingsPlanner/SavingsPlanner.test.js
src/Utilities/__fixtures__/index.js
src/Utilities/__fixtures__/preflightRequest200.js
src/Utilities/__fixtures__/preflightRequest401.js
src/Utilities/__fixtures__/preflightRequest403.js
src/Utilities/__fixtures__/preflightRequest404.js
src/Utilities/__fixtures__/readClusterOptions.js
src/Utilities/__fixtures__/readEventExplorer.js
src/Utilities/__fixtures__/readJobExplorer.js
src/Utilities/__fixtures__/readPlans.js
src/Utilities/__fixtures__/readPlansOptions.js
src/Utilities/tests/helpers.reactTestingLib.js

Apologies this PR seems a little busier than it actually is - a lot of this is linter fixes on existing test files.

Add unit tests savings planner list view

---

src/Containers/OrganizationStatistics/OrganizationStatistics.test.js
src/Utilities/Legend.test.js
src/Utilities/constants.js
src/Utilities/useQueryParams.js

I missed committing this somehow in the original PR...

Added missing handlers for inventory id

---

src/Charts/BaseChart.js

Wrap each chart with React's withRouter HOC to fix redirects.
https://issues.redhat.com/browse/AA-532

Fix AA-532 Re-enable redirecting from click through

---

src/Components/TemplatesList.js

https://issues.redhat.com/browse/AA-536

Adjust aria label to either "template" or "workflow".

---

src/Components/EmptyList.js
src/Components/EmptyList.test.js
src/Containers/SavingsPlanner/SavingsPlanner.js
src/Containers/SavingsPlanner/SavingsPlanner.test.js

This component will be displayed when there are no records to display on the page, along with Add button(if user has access to Add new records)
https://issues.redhat.com/browse/AA-543

Added EmptyList component to show message and Add button

---

src/Charts/BarChart.js
src/Charts/LineChart.js
src/Containers/Clusters/Clusters.js

https://issues.redhat.com/browse/AA-533

[AA-533] Pass queryParams through Clusters page when redirecting to Job Explorer

---

package.json
src/Api.js
src/Charts/BarChart.js
src/Charts/GroupedBarChart/GroupedBarChart.js
src/Charts/GroupedBarChart/OrgsTooltip.js
src/Charts/LineChart.js
src/Charts/PieChart.test.js
src/Components/AlertModal/AlertModal.js
src/Components/AlertModal/AlertModal.test.js
src/Components/Breadcrumbs.js
src/Components/CardActionsRow.js
src/Components/DeleteButton/DeleteButton.js
src/Components/DeleteButton/DeleteButton.test.js
src/Components/EmptyList.js
src/Components/EmptyList.test.js
src/Components/EmptyState.js
src/Components/ErrorDetail/ErrorDetail.js
src/Components/ErrorDetail/ErrorDetail.test.js
src/Components/RoutedTabs.test.js
src/Components/Toolbar/Toolbar.js
src/Components/Toolbar/ToolbarDeleteButton.js
src/Components/Toolbar/ToolbarDeleteButton.test.js
src/Containers/SavingsPlanner/SavingsPlanner.js
src/Containers/SavingsPlanner/SavingsPlanner.test.js
src/Utilities/getRelatedResouceDeleteDetails.test.js
src/Utilities/getRelatedResourceDeleteDetails.js
src/Utilities/helpers.test.js
src/Utilities/useRequest.js
src/Utilities/useSelected.js
src/Utilities/useSelected.test.js

This PR fixes linting, lots of problems with default values and prop type checking, and also moves the pagination on the savings planner page under the cards, so it is les confusing. Further work probably could make it better, but we were not so nitpicking this time.

Fixing linting

---

src/Components/ModalContents.js
src/Components/ModalContents.test.js
src/Components/TemplatesList.js

Effectively eliminates persistent job and stat display occuring after clicking on another modal popup.

Clear Modal state upon closing

---

package-lock.json
package.json
src/Containers/SavingsPlanner/Details/StatisticsTab/TotalSavings/index.tsx
src/Containers/SavingsPlanner/Details/StatisticsTab/index.tsx
src/Containers/SavingsPlanner/List/ListItem/index.js
src/Containers/SavingsPlanner/Shared/currencyFormatter.ts
src/Containers/SavingsPlanner/Shared/hoursFormatter.ts

Updating the chart tooltip + currecny formatter

---

src/Components/EmptyList.js
src/Containers/SavingsPlanner/List/List.js

The icon prop was giving prop validation errors. I could not get the icon to pass correctly but since the empty list is already pretty specific with the add button, I moved the icon there, and now all bad red errors are gone from the console.

Fixed prop icon undefined passed error on savings empty list

---

src/App.js

jira: https://issues.redhat.com/browse/RHCLOUD-15238
Causes chrome left navigation to fail.

Fix invalid hook call.

---

src/Components/ModalContents.js
src/Components/ModalContents.test.js

- And fixed to load correct contents in modal when template/wokflow is selected
@knightsean00 this addresses the bug you found. @jlmitch5 please review.

- split useRequest requests into individual requests

---

src/Api/methods.ts

The new backend packages will need this to work correctly.

Added content header for our calls

---

src/Api/api.ts
src/Api/methods.ts
src/Api/types.ts
src/Containers/SavingsPlanner/Details/DetailsTab/index.js
src/Containers/SavingsPlanner/List/List.js

David added a new endpoint for deleting multiple plans. See: 
https://issues.redhat.com/browse/AA-652
https://issues.redhat.com/browse/AA-671

Fixed delete multiple errors by adding a new endpoint for deleting

---

src/Containers/JobExplorer/JobExplorerListRow.js

The issue was introduced in https://github.com/RedHatInsights/tower-analytics-frontend/pull/498
before fix
after fix

Put the link back on Id/Name cells.

---

src/Api/methods.ts

https://issues.redhat.com/browse/AA-728

Added slashes to the update and delete urls hoping to fix prod delete endpoint

---

package-lock.json
src/Components/Error404.tsx
src/Containers/OrganizationStatistics/OrganizationStatistics.js
src/Containers/Reports/Details/Details.tsx
src/Containers/Reports/List/ListItem/index.js
src/Containers/Reports/ReportsRouter.tsx
src/Containers/Reports/Shared/schemas/index.ts
src/Containers/Reports/index.ts
src/Containers/Reports/paths.ts

The error page when opening a non existent report (we could use this for non existent urls in the router too probably)

Added a 404 page and the reports starts to use it

---

.travis/custom_release.sh

* With these changes I would also like to delete the following branches:
* ci-beta
* qa-beta
* qa-stable
* prod-beta
to avoid confusion in deployment

Changed the custom config to deploy dev to stage

---

src/Containers/Reports/Details/Report.tsx
src/Containers/Reports/Shared/schemas/templates_explorer.ts

Fixed Y axis label to be dynamic to match the sort column
Before
After

Updated description for Templates Explorer report

---

package-lock.json
package.json
src/Components/Toolbar/DownloadPdfButton.js

* Removed a package we ended up not using at processing data streams
* Removed an unnecesarry comment I made for Salma
* Corrected the PropTypes for the Download button
* Removed an extra wrapper around the Download Button

Fixes after PR #603

---

src/Containers/Clusters/ModalContents.js

Added date to the redirect after Zvika's feedback.

Added date range to the modal redirect from clsters to job explorer

---

Dockerfile
build_deploy.sh
pr_check.sh

Part of the pr check pipeline work for UI
Related to: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/27918

UI pr check pipeline

---

package-lock.json
package.json
src/Containers/AutomationCalculatorNew/AutomationCalculator.js
src/Containers/AutomationCalculatorNew/Chart/chartSchema.ts
src/Containers/AutomationCalculatorNew/Chart/index.tsx

**After the chart is looking like this**
P.S.: Waiting for @trahman73 to approve

[AA-846] Change the new roi page chart

---

src/Containers/JobExplorer/JobExplorer.js
src/Containers/JobExplorer/JobExplorer.test.js

Expose error state when custom date range value is beyond 62 days.
Current:
Fix:

[aa-882] Job Explorer Custom Date Range Bugfix

---

src/Containers/Reports/Shared/schemas/mostUsedModules.ts

Added the option to filter by module in the most used modules report.
Jira issue: https://issues.redhat.com/browse/AA-904
Before: 
After:

Added filter by module option

---

src/Containers/Reports/Shared/schemas/automationCalculator.ts

Added description to ROI report

---

cypress.json
cypress/integration/Dashboard.spec.js
cypress/integration/Reports.spec.js
cypress/support/commands.js

Additionally add option for using different login flow for
keycloak sites like localhost and ephemeral.

Fix failing cypress tests

---

src/FeatureFlags/useFeatureFlag.ts

And add the ephemeral environment as a devel environment.
See the code comments how the new logic works. This should enable more precise testing, while not disturbing or changing any of the current workflows.

Change the logic how the FF works in devel env

---

src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.js
src/Containers/Reports/Layouts/Standard/Components/ExtendedTableRow/TemplatesExplorer.tsx
src/Containers/Reports/Layouts/Standard/Components/ExtendedTableRow/index.ts
src/Containers/Reports/Layouts/Standard/Components/ExtendedTableRow/types.ts
src/Containers/Reports/Layouts/Standard/Components/index.ts
src/Containers/Reports/Layouts/Standard/ReportCard.tsx
src/Containers/Reports/Layouts/Standard/Table/TableRow.tsx
src/Containers/Reports/Layouts/Standard/Table/index.tsx
src/Containers/Reports/Shared/schemas/aa21OnboardingReport.ts
src/Containers/Reports/Shared/schemas/affectedHostsByPlaybook.ts
src/Containers/Reports/Shared/schemas/automationCalculator.ts
src/Containers/Reports/Shared/schemas/changesMade.ts
src/Containers/Reports/Shared/schemas/hostsByOrganizations.ts
src/Containers/Reports/Shared/schemas/jobsTasksByOrganization.ts
src/Containers/Reports/Shared/schemas/moduleUsageByJobTemplate.ts
src/Containers/Reports/Shared/schemas/moduleUsageByOrganization.ts
src/Containers/Reports/Shared/schemas/moduleUsageByTask.ts
src/Containers/Reports/Shared/schemas/mostUsedModules.ts
src/Containers/Reports/Shared/schemas/playbookRunRate.ts
src/Containers/Reports/Shared/schemas/templatesExplorer.ts
src/Containers/Reports/Shared/types.ts

Waiting for #681 
This PR makes the expanded table row swappable in the future, while keeping the schema DB friendly.

[AA-927] Extended row mapper

---

src/Api/types.ts
src/Components/Toolbar/DownloadPdfButton.tsx

Connected MR's:
* https://gitlab.cee.redhat.com/automation-analytics/pdf-generator/-/merge_requests/65
* https://gitlab.cee.redhat.com/automation-analytics/automation-analytics-backend/-/merge_requests/303

Make pdf params more passtrough

---

.eslintrc.json
src/Charts/LineChart.js
src/Components/Toolbar/ToolbarDeleteButton.js
src/Containers/SavingsPlanner/Shared/Form/index.js

Updating eslint rules and files - no use before defined: error

---

src/Api/types.ts
src/Components/Toolbar/DownloadPdfButton.tsx
src/QueryParams/index.ts
src/QueryParams/useReadQueryParams.ts

Waiting fot backend and PDF gen repos: [(MR)](https://gitlab.cee.redhat.com/automation-analytics/pdf-generator/-/merge_requests/67)
This PR cannot be merged without the backend part. The backend part can be merged without this.
[hosts_changed_by_job_template_1_4_2022 (2).pdf](https://github.com/RedHatInsights/tower-analytics-frontend/files/7807050/hosts_changed_by_job_template_1_4_2022.2.pdf)

[Needs #692] Add hidden series information to the PDF call

---

src/Components/Toolbar/Groups/FiltersCategoriesGroup.tsx
src/Components/Toolbar/Toolbar.tsx
src/Containers/Reports/Layouts/Standard/ReportCard.tsx
src/Containers/Reports/Shared/schemas/moduleUsageByJobTemplate.ts
src/Containers/Reports/Shared/schemas/moduleUsageByOrganization.ts
src/Containers/Reports/Shared/schemas/moduleUsageByTask.ts
src/Containers/Reports/Shared/types.ts

And make the reports to use it when some of them has a default
module instead of status selected

Added an option to define the default selected filter

---

src/Containers/Reports/Shared/schemas/moduleUsageByJobTemplate.ts
src/Containers/Reports/Shared/schemas/moduleUsageByOrganization.ts
src/Containers/Reports/Shared/schemas/moduleUsageByTask.ts
src/Containers/Reports/Shared/schemas/mostUsedModules.ts

https://issues.redhat.com/browse/AA-808
Depends on: https://gitlab.cee.redhat.com/automation-analytics/automation-analytics-backend/-/merge_requests/320

Added total_count column to all Module reports

---

src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.test.js
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx

UI changes to address changes in API response in https://gitlab.cee.redhat.com/automation-analytics/automation-analytics-backend/-/merge_requests/315
https://issues.redhat.com/browse/AA-958
@AparnaKarve please review

Used data in meta['legend'] instead of items from API response

---

Makefile
sonarqube.sh

Scan visible at
https://ci.int.devshift.net/job/RedHatInsights-tower-analytics-frontend-sonarqube-pr-check/
https://sonarqube.corp.redhat.com/dashboard?id=tower-analytics-frontend

Enable sonarqube scans on frontend artifacts

---

src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
src/Containers/Reports/Layouts/AutomationCalculator/CalculationCost.test.js
src/Containers/Reports/Layouts/AutomationCalculator/CalculationCost.tsx
src/QueryParams/__tests__/useQueryParams.test.js
src/QueryParams/useQueryParams.js

Fixes https://issues.redhat.com/browse/AA-850

 ROI report has persistent inputs

---

src/Api/types.ts
src/Components/Toolbar/DownloadPdfButton.tsx
src/Containers/Reports/Layouts/Standard/ReportCard.tsx

Display filters on PDF download

---

src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx

AA PDF Download Error Fix

---

src/Containers/Reports/Shared/schemas/index.ts

Added console.logs to reports to be able to better investigate sporadic 404 error on reports in stage.
Jira issue: https://issues.redhat.com/browse/AA-988

Added logs to reports

---

src/Containers/Reports/Details/index.tsx
src/Containers/Reports/Shared/schemas/index.ts
src/FeatureFlags/useFeatureFlag.ts

Added more console.logs to investigate temporary 404 error on stage reports and attempted to solve the issue- will need to merge to stage to see if it works (issue cannot be recreated locally).
Jira issue:  https://issues.redhat.com/browse/AA-988

Debugging reports 404 error and attempt to fix

---

src/Api/api.ts

Trying a different method of fixing 404 error on reports

404 error fix

---

src/Api/types.ts
src/Components/Toolbar/DownloadPdfButton.tsx
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
src/Containers/Reports/Layouts/Standard/ReportCard.tsx

Frontend changes to add date/granularity and sort information to report pdf
Jira issue: https://issues.redhat.com/browse/AA-1008
Associated MR: https://gitlab.cee.redhat.com/automation-analytics/pdf-generator/-/merge_requests/82
[templates_explorer_2_15_2022.pdf](https://github.com/RedHatInsights/tower-analytics-frontend/files/8074702/templates_explorer_2_15_2022.pdf)
[hosts_changed_by_job_template_2_15_2022.pdf](https://github.com/RedHatInsights/tower-analytics-frontend/files/8074704/hosts_changed_by_job_template_2_15_2022.pdf)

Frontend changes for pdf updates

---

src/Api/types.ts
src/Components/Toolbar/DownloadPdfButton.tsx
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
src/Containers/Reports/Layouts/Standard/ReportCard.tsx

Reverts RedHatInsights/tower-analytics-frontend#752

Revert "Frontend changes for pdf updates"

---

config/ansible-navigation.json
src/Containers/Reports/Details/index.tsx
src/Containers/Reports/paths.ts
src/Routes.tsx
src/paths.js

Changes to make Automation Calculator in left menu to point to new ROI report
Fixes https://issues.redhat.com/browse/AA-1046

AA-1046 - Updated ROI menu in left navigation

---

src/Components/Toolbar/DownloadPdfButton.tsx
src/Components/Toolbar/EmailDetailsForm.tsx

- Added search to Recipient dropdown.
- Show no users associated with the selected group when there are no email addresses associated
Backend MR related to these changes https://gitlab.cee.redhat.com/automation-analytics/automation-analytics-backend/-/merge_requests/359

Reset email modal after email is sent

---

src/Components/Toolbar/DownloadPdfButton.tsx
src/FeatureFlags/types.ts

Gated send email feature

---

src/App.js

Temporary styling fix to hide the global filter.

Hide global filter

---

src/Components/Toolbar/DownloadButton/Steps/EmailDetails/SendEmail.tsx
src/Components/Toolbar/DownloadButton/Steps/EmailDetails/index.tsx

- Fixed value of expiry field to be sent up to backend
@AparnaKarve @appuk 
before
after
https://issues.redhat.com/browse/AA-1146

Disable past dates on Expiry date selection

---

src/Components/Toolbar/DownloadButton/index.tsx

@AparnaKarve please test/review

Fixed to send inputs along with queryParams

---

src/Components/ApiStatus/ApiStatusWrapper.tsx
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.test.js

Display a message when custom date range is > 62 days in report

---

src/Routes.tsx

Moved redirect after the actual routes

Fix: Add a redirect for the root route to the Routes

---

cypress/support/commands.js

- also comment out iframe code
- will be used locally only if necessary

[cypress] Update login URL assertion

---

src/Charts/BarChart.js
src/Components/Toolbar/Groups/CategoryDropdown.tsx
src/Containers/Clusters/Clusters.test.js
src/Containers/Reports/Layouts/Standard/Table/index.tsx
src/Containers/Reports/List/List.tsx
src/Containers/Reports/List/ListItem/index.tsx
src/Containers/SavingsPlanner/Shared/Form/Steps/Templates/index.js
src/Containers/SavingsPlanner/Shared/Form/Steps/Templates/index.test.js

Replace data-testid with data-cy

---

cypress/e2e/Global.spec.js
cypress/support/commands.js
cypress/support/constants.js

This is a first PR of the series to fix our existing Cypress tests running in our pipeline.
<br>
This one includes:
- Fix login flow
- Include new fixtures to reduce the verbosity of the tests
- Update and fix Global tests (still room for more assertions)

[cypress] Update fixtures and Global test

---

cypress/e2e/AutomationCalculator.spec.js
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
src/Containers/Reports/Layouts/AutomationCalculator/AutomationFormula.tsx
src/Containers/Reports/Layouts/AutomationCalculator/TemplatesTable/Row.tsx
src/Containers/Reports/Layouts/AutomationCalculator/TemplatesTable/index.tsx
src/Containers/Reports/Layouts/AutomationCalculator/TotalSavings.tsx

TODO test:
Fixes https://issues.redhat.com/browse/AA-1087
cc: @fullsushidev

Add automation calculator test

---

cypress/e2e/Global.spec.js
src/Components/ApiStatus/ApiErrorState.tsx
src/Components/ApiStatus/AuthorizationErrorPage.tsx
src/Components/Error404.tsx
src/Routes.tsx
src/Utilities/asyncComponent.js

Add check that pages do not render 400/500 errors 

---

cypress/support/commands.js

- Adds path to the login strategy to accept cookie dialogue 
- Different landing page for frontend operator strategy

login strategy additional options

---

src/Components/Pagination/Pagination.tsx
src/Containers/Reports/Details/index.tsx

Add data cy to pagination and labels

---

package-lock.json
package.json

Updating react-json-chart builder library from `^1.10.2` to `^1.13.0`

Bump react chart builder library version

---

cypress/e2e/Clusters.spec.js
src/Components/Toolbar/Toolbar.tsx
src/Containers/Clusters/Clusters.js

- Added `data-cy` attributes to be used in tests
@ZitaNemeckova pls review

Added Cypress tests for Clusters page

---

cypress/e2e/Reports.spec.js
cypress/support/commands.js
src/Components/ApiStatus/ApiStatusWrapper.tsx
src/Containers/Reports/Layouts/Standard/ReportCard.tsx
src/Containers/Reports/List/List.tsx

Reports Home Page:
Short Report View
Outside of the issue:
Blocked by https://issues.redhat.com/browse/AA-1298

AA1250 test reports

---

cypress/e2e/AutomationCalculator.spec.js
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx

Continuation of https://github.com/RedHatInsights/tower-analytics-frontend/pull/847
Table is updated when Manual/Automation cost or manual time is changed.
Fixes https://issues.redhat.com/browse/AA-1259

Updated: AA-1259 ROI Update Table Values

---

src/Containers/Reports/List/List.tsx
src/QueryParams/useQueryParams.js

Fixes https://issues.redhat.com/browse/AA-1379 and https://issues.redhat.com/browse/AA-1378
Steps to reproduce
- Go to Reports
- selected a report
- refresh the page
Before:
it crashed 
After:
reloads the page and selected report is in preview

Save slug of the previewed report to the URL

---

cypress/e2e/AutomationCalculator.spec.js
cypress/e2e/Clusters.spec.js
cypress/e2e/Dashboard.spec.js
cypress/e2e/Global.spec.js
cypress/e2e/JobExplorer.spec.js
cypress/e2e/Notifications.spec.js
cypress/e2e/OrganizationStatistics.spec.js
cypress/e2e/Reports.spec.js
cypress/e2e/SavingsPlanner.spec.js
cypress/e2e/reports/AA2Migration.spec.js
cypress/e2e/reports/ChangesMadeByJobTemplate.spec.js
cypress/e2e/reports/HostAnomaliesBar.spec.js
cypress/e2e/reports/HostsByOrganization.spec.js
cypress/e2e/reports/HostsChangedByJobTemplate.spec.js
cypress/e2e/reports/JobTemplateRunRate.spec.js
cypress/e2e/reports/JobsTasksByOrganization.spec.js
cypress/e2e/reports/ModuleUsageByJobTemplate.spec.js
cypress/e2e/reports/ModuleUsageByOrganization.spec.js
cypress/e2e/reports/ModuleUsageByTask.spec.js
cypress/e2e/reports/MostUsedModules.spec.js
cypress/e2e/reports/TemplatesExplorer.spec.js
cypress/fixtures/tables_pagination.json
cypress/support/commands.js
cypress/support/e2e.js
cypress/support/login.js

Depends on #871 
ref.: https://docs.cypress.io/guides/references/best-practices#Using-after-or-afterEach-hooks

Fix before/after each rook

---

src/Containers/Clusters/ModalContents.js

Adds `data-cy` to Cancel and View All Jobs buttons in modal on Cluster page
@fullsushidev

Add data-cy to buttons in Cluster modal

---

cypress.config.ts
cypress/e2e/AutomationCalculator.spec.js
cypress/e2e/Clusters.spec.js
cypress/e2e/Dashboard.spec.js
cypress/e2e/Global.spec.js
cypress/e2e/JobExplorer.spec.js
cypress/e2e/Notifications.spec.js
cypress/e2e/OrganizationStatistics.spec.js
cypress/e2e/Reports.spec.js
cypress/e2e/SavingsPlanner.spec.js
cypress/e2e/reports/AA2Migration.spec.js
cypress/e2e/reports/ChangesMadeByJobTemplate.spec.js
cypress/e2e/reports/HostAnomaliesBar.spec.js
cypress/e2e/reports/HostsByOrganization.spec.js
cypress/e2e/reports/HostsChangedByJobTemplate.spec.js
cypress/e2e/reports/JobTemplateRunRate.spec.js
cypress/e2e/reports/JobsTasksByOrganization.spec.js
cypress/e2e/reports/ModuleUsageByJobTemplate.spec.js
cypress/e2e/reports/ModuleUsageByOrganization.spec.js
cypress/e2e/reports/ModuleUsageByTask.spec.js
cypress/e2e/reports/MostUsedModules.spec.js
cypress/e2e/reports/TemplatesExplorer.spec.js
cypress/fixtures/tables_pagination.json
cypress/support/commands.js
cypress/support/constants.js
cypress/support/e2e.js
cypress/support/login.js
cypress/support/pagination.js

This PR is a combination of:
- https://github.com/RedHatInsights/tower-analytics-frontend/pull/872
- https://github.com/RedHatInsights/tower-analytics-frontend/pull/874
- and https://github.com/RedHatInsights/tower-analytics-frontend/pull/876
It's easier to review it by navigating through each commit instead of the entire code.

Cypress devel

---

cypress/e2e/AutomationCalculator.spec.js
cypress/e2e/Dashboard.spec.js
cypress/e2e/Reports.spec.js
cypress/e2e/reports/HostAnomaliesBar.spec.js
cypress/fixtures/tables_pagination.json
cypress/support/commands.js
cypress/support/e2e.js
cypress/support/login.js
cypress/support/pagination.js

This PR includes changes in 9 files, so each commit is fixing one problem at a time.
depends on https://github.com/RedHatInsights/tower-analytics-frontend/pull/875

Fix cypress flaky tests

---

README.md

Needs https://gitlab.cee.redhat.com/automation-analytics/automation-analytics-backend/-/merge_requests/601 for backend instructions.

Add instructions for M1 Mac to README

---

src/App.js

Removed alert that was added in https://issues.redhat.com/browse/AA-1472
https://issues.redhat.com/browse/AA-1491
before
after
/cc @slemrmartin

Removed data processing alert message

---

src/Api/api.ts
src/Api/methods.ts
src/Containers/SavingsPlanner/Shared/Form/index.js

Bug fix to display the correct component on all pages when a customer is not sending data to analytics. Some additional changes have been made to ensure the correct behavior occurs when there is data and a customer wants to add a plan in savings planner.
Jira issue: https://issues.redhat.com/browse/AA-1473
Before: 
After:

[AA-1473] Authorization error fix

---

cypress.config.ts
cypress/README.md
cypress/support/e2e.js
cypress/support/login.js
package-lock.json
package.json

Small adjustment to make cypress load the cookies before start the login process. This removes the necessity to click on the iframe to accept cookies.
Depends on #910

Update cookies for cypress > v12

---

src/Components/Toolbar/Groups/ToolbarInput/Select.tsx

Show filter and show entries from all the entries that were received from backend API. We're continuing to show 500 entries only to avoid performance issues while rendering drop-down with 5000 entries.
https://issues.redhat.com/browse/AA-1554
Backend PR https://gitlab.cee.redhat.com/automation-analytics/automation-analytics-backend/-/merge_requests/678

Show first 500 entries in drop down

---

config/prod.webpack.config.js

See http://front-end-docs-insights.apps.ocp4.prod.psi.redhat.com/blog/router-v6#Markyourreact-router-domdependencyasasingletoninthemodulefederationplugin for more info

Make sure react-router-dom is a singleton on prod

---

src/Components/Toolbar/Groups/ToolbarInput/Date.tsx
src/QueryParams/useQueryParams.js
src/Utilities/helpers.ts

Jira issue: https://issues.redhat.com/browse/AA-1649
This PR fixes the custom date selection component. Previously an error would occur when the user tried to select a custom date. This fix passes in event and selected date value, newer version of DatePicker expects onChange event to pass in an additional first parameter as event.

[AA-1649] Fix custom date range selection

---

src/Components/Toolbar/Groups/ToolbarInput/Date.tsx
src/QueryParams/useQueryParams.js
src/Utilities/helpers.ts

Reverts RedHatInsights/tower-analytics-frontend#941

Revert "[AA-1649] Fix custom date range selection"

---

src/Components/Toolbar/Groups/ToolbarInput/Date.tsx
src/Containers/OrganizationStatistics/OrganizationStatistics.test.js
src/QueryParams/useQueryParams.js
src/Utilities/helpers.ts

Jira issue: https://issues.redhat.com/browse/AA-1649
This PR fixes the custom date selection component. Previously an error would occur when the user tried to select a custom date. This fix passes in event and selected date value, newer version of DatePicker expects onChange event to pass in an additional first parameter as event.

[AA-1649] Fix custom date selection

---

src/Components/Toolbar/DownloadButton/Steps/PdfDetails/PdfDownload.tsx
src/Components/Toolbar/DownloadButton/index.tsx
src/Components/Toolbar/types.ts
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx

Jira issue: https://issues.redhat.com/browse/AA-1641
Pdf-generator MR: https://gitlab.cee.redhat.com/automation-analytics/pdf-generator/-/merge_requests/136
Removes themeColor from props passed into pdf generator.

AA-1641 - Change chart color without passing themeColor

---

src/App.js

https://issues.redhat.com/browse/AA-1802

Add alert message when backend is slow

---

src/App.js

Removes delayed data banner from crc ui
Jira issue: https://issues.redhat.com/browse/AA-1856

[AA-1856] Remove alert banner

---

cypress/e2e/AutomationCalculator.spec.js
cypress/e2e/Clusters.spec.js
cypress/e2e/Global.spec.js
cypress/e2e/Notifications.spec.js
cypress/e2e/Reports.spec.js
cypress/e2e/ReportsPage.spec.js
cypress/e2e/SavingsPlanner.spec.js

Temporary fixes for ephemeral cypress tests

Temporary ephemeral fixes for broken tests

---

package-lock.json
package.json
src/Containers/Reports/List/List.tsx
src/Containers/Reports/List/ListItem/index.tsx

Jira issue: https://issues.redhat.com/browse/AA-1791
Reduces number of API calls made when clicking on a report card to show preview of that report.

[AA-1791] Fix excessive api calls in report list

---

src/Routes.tsx

Jira issue: https://issues.redhat.com/browse/AA-1911

Remove the extra slash

---

package-lock.json
src/Charts/BarChart.js
src/Charts/LineChart.js
src/Containers/SavingsPlanner/List/ListItem/index.js

This PR fixes redirects from charts and savings planner list view to the job explorer page.
Jira issue: https://issues.redhat.com/browse/AA-1927

[AA-1927] Fix broken redirects in stage/prod

---

.github/workflows/devel.yml
package-lock.json

Sync devel to master.
the frontend operator pipeline is designed to run on main/master branch push/merge events.
Because patches are landing onto devel, the pipeline won't run, and the latest updates won't appear on stage.
This github action automatically syncs devel to master on merge.

Github action sync to master branch on push

---

src/Containers/Reports/List/ListItem/index.tsx
src/Containers/SavingsPlanner/List/ListItem/index.js

This PR fixes both card styling issues described in this document: https://docs.google.com/document/d/17bPlqO2emd9o9vTyCMLuIoDMA6ZtYcoVQnLfm5cy7DE/edit#heading=h.chbmjc3dy1r4

Card styling fixes

---

src/Api/api.ts
src/Charts/Breakdown.js
src/Components/Toolbar/DownloadButton/Steps/EmailDetails/index.tsx
src/Components/Toolbar/DownloadButton/index.tsx
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
src/Containers/Reports/Layouts/Standard/Components/ExtendedTableRow/HostAnomalies.tsx
src/Containers/Reports/Layouts/types.ts
src/Containers/Reports/List/List.tsx
src/Containers/SavingsPlanner/Shared/Form/Steps/Tasks/index.js

Means 0 remaining issues.
.. except for tests :)

Fix remaining typescript & eslint issues

---

src/Containers/Notifications/Notifications.tsx

Fixes the layout of the dropdown filters in notifications and also fixes the issue with the click target being only on the label

Fix layout of dropdown items

---

.github/workflows/pr.yml
package-lock.json

Forgot to update package-lock.json in #1059 , fixing.
And add a PR check to fail when `package.json` and `package-lock.json` don't match.

update package-lock, add PR check that package-lock matches

---

.github/workflows/devel.yml

This workflow creates PRs updating master from devel.
If a PR already exists, it gets updated, otherwise a new one is created.
Changes to devel would deploy to stage,
changes to master would deploy to prod.

Restore devel -> master sync workflow

---

src/Components/DeleteButton/DeleteButton.js
src/Containers/SavingsPlanner/Details/DetailsTab/index.js

Fixes https://issues.redhat.com/browse/AAP-32263
Before:
After:

Fix buttons in Savings planner detail page

---

src/Components/ApiStatus/AuthorizationErrorPage.tsx

Jira issue: https://issues.redhat.com/browse/AAP-43671
Replaces old link with up to date link to relevant docs.

[AAP-43671] Fix doc link

---

package-lock.json

[AAP-50377](https://issues.redhat.com/browse/AAP-50377)
Ran `npm audit fix` to update form-data among other dependencies

[AAP-50377] npm audit fix
