src/SmartComponents/SamplePage/SamplePage.js

Turns out `100vh` is not the height we want. It can cause background bugs like this if your browser height isn't maximized:
This PR reverts the CSS changes that caused this new visual regression.

Revert CSS changes until afer fest.

---

src/Components/EmptyState.js

For non-`401/404` errors we should show a default message to the user.

Add default empty state.

---

src/Utilities/Tooltip.js

Band-aid fix for narrow tooltip width.
related: https://github.com/RedHatInsights/tower-analytics-backend/issues/30
A more permanent fix to come later.

Manually bump tooltip width.

---

src/SmartComponents/SamplePage/sample-page.scss
src/Utilities/Tooltip.js

- Adjust spacing of visual elements to accommodate for toolbar width increase.
- Remove blue border when app panel is clicked on.
This PR addresses a visual regression in which a flipped toolbar would hide the tooltip pointer:
It also removes the blue border when a card panel is clicked on within the UI:

Some small styling tweaks.

---

src/Charts/GroupedBarChart.js
src/Utilities/Tooltip.js

Scale the tooltip width to accommodate for dynamic data.

Refactor tooltips to have dynamic widths.

---

.eslintrc.yml
src/Api.js
src/Charts/LineChart.js
src/Charts/PieChart.js
src/Containers/Clusters/Clusters.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js
src/Utilities/useQueryParams.js
src/Utilities/useQueryParams.test.js

As a continuation of PR #51, this PR abstracts the `useReducer` hook created in the Clusters view into a generalized, reusable hook that handle how page parameters should be packaged in order to be digested by the API.
Note #51 should be merged before merging this one.

Reusable queryparams hook

---

src/Components/TemplatesList.js
src/Containers/Clusters/Clusters.js

This PR replaces all instances of `system_id` and `system_uuid` in the UI and replaces them with `cluster_id` and `install_uuid` respectively.

Update UI usage of API fields for upcoming Clusters API change

---

src/Utilities/useQueryParams.js
src/Utilities/useQueryParams.test.js

- Refactor how dates are calculated using built-in timespans rather than calculating that manually
- Remove id from queryParams object if passed in value is a string

Some updates to useQueryParams reducer:

---

src/Containers/OrganizationStatistics/OrganizationStatistics.js
src/Utilities/useQueryParams.js
src/Utilities/useQueryParams.test.js

Related: https://github.com/RedHatInsights/tower-analytics-backend/pull/197
This PR changes `orderBy` params:
- use `sort_by`
- specify column ordering
- add `limit`; defaults to 200 results
examples:
`sort_by=count:asc`
`sort_by=count:desc&limit=5`
If a user toggles View All (Orgs), then the UI will not specify an `sort_by` param and uses the default limit.

Change orderby to ipp standards

---

src/Components/ModulesList.js
src/Components/NoData.js
src/Components/NotificationsList.js
src/Components/TemplatesList.js
src/Containers/Clusters/Clusters.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js

Related: https://github.com/RedHatInsights/tower-analytics-frontend/issues/49
Currently our app shows the same loading state if the API returns empty results. This PR fixes that by creating a NoData component to render:
Before:
After:

Add emptystate and loading state for Clusters and Org Stats views

---

src/Containers/AutomationCalculator/AutomationCalculator.js

Linked issue: https://github.com/RedHatInsights/tower-analytics-backend/issues/346
This PR handles standardizing float values (`elapsed_sum, successful_elapsed_sum, failed_elapsed_sum) rendered in the tooltip on the top templates card  to the second decimal place.

Standardize decimal up to second decimal place using toFixed().

---

src/Charts/ROITopTemplates.js
src/Containers/AutomationCalculator/AutomationCalculator.js
src/Containers/AutomationCalculator/AutomationCalculator.test.js

Related #111 
This PR changes the graph representing template elapsed run time (manual vs automated) to a single bar chart representing savings per template.

Convert to single bar chart with updated tooltips showing savings.

---

src/Charts/ROITopTemplates.js

Related #120 
This PR adjusts the y axis on the automation calculator chart to accommodate large numbers.

Adjust y axis labels to accomodate large numbers.

---

src/Containers/Notifications/Notifications.js

Linked issue: https://slack-redir.net/link?url=https%3A%2F%2Fgithub.com%2FRedHatInsights%2Ftower-analytics-frontend%2Fissues%2F113
This PR handles updating the section prompt for clusters on the notifications page.

Update the dropdown menu prompt for clusters 

---

src/Containers/AutomationCalculator/AutomationCalculator.js

Linked issue: https://slack-redir.net/link?url=https%3A%2F%2Fgithub.com%2FRedHatInsights%2Ftower-analytics-frontend%2Fissues%2F112
This PR handles swapping the eye icon with the toggle on/off icon on the top templates card for clearer intended use.

Replace eye icon with toggle on/off icons

---

src/Containers/AutomationCalculator/AutomationCalculator.js

Related issue: https://github.com/RedHatInsights/tower-analytics-frontend/issues/118
This PR handles fixing the bottom alignment of the automation formula and top templates cards. The top templates card now has a maxHeight style attribute which should keep that card at fixed height when the browser window resizes.

Fix card bottom alignment by passing maxHeight to job template card

---

src/Charts/ROITopTemplates.js
src/Containers/AutomationCalculator/AutomationCalculator.js

This PR adjusts both logic and styling in `AutomationCalculator.js` and `ROITopTemplates.js` so that the correct component is selected to render the chart (if more than 15 templates are returned) and to adjust its overflow style accordingly.

Fix chart not being able to find correct container

---

src/Containers/AutomationCalculator/AutomationCalculator.js

linked issue: https://github.com/RedHatInsights/tower-analytics-frontend/issues/131
This PR handles preventing users from manually entering negative values into the automation cost inputs on the ROI calculator.

Prevent users from manually entering negative values 

---

src/Charts/BarChart.js
src/Charts/BaseChart.js
src/Charts/GroupedBarChart.js
src/Charts/LineChart.js
src/Charts/PieChart.js
src/Charts/tests/Chart.test.js
src/Charts/tests/__snapshots__/Chart.test.js.snap

Closes: #94 closes #102 closes #103 and closes #104
Converts the `BarChart`, `GruppedBarChart`, `LineChart`, `PieChart` to a functional component.
Coverts `BaseChart` to a functional component and fixes a console error where the `propTypes` were declared inside the component instead of after.
No UI changes as far as I tested it well.

Converting charts to functional components

---

src/Charts/GroupedBarChart.js
src/Charts/LineChart.js
src/Charts/ROITopTemplates.js
src/Components/TemplatesList.js
src/Containers/AutomationCalculator/AutomationCalculator.js
src/Utilities/Tooltip.js

Addresses https://github.com/RedHatInsights/tower-analytics-frontend/issues/65
I hacked together a quick pyscript to look for more instances of strings that are not in sentence case:
https://gist.github.com/jctanner/96f8035d69f3ecad4d2d43e65ea51206
It's not perfect and I'm not sure if -every- string was supposed to be sentence cased, but hopefully this PR can be reviewed and I can fix what isn't correct.

more sentence casing

---

src/App.scss
src/Components/ModulesList.js
src/Components/TemplatesList.js

This fixes #166 Fixes a vertical alignment issue on the templates and modules list.

Fixes padding issue on templates list and modules list

---

src/Components/TemplatesList.js

This PR fixes issue #167. @AlexSCorey's fix for #166 has been merged into this PR which fixes the template details modal datalist header alignments also mentioned in #167.

Fix padding on template details modal

---

src/Utilities/Legend.js

Closes #180 
Fixed the switch display problem. I could not test on other OS just on Fedora and since it was a specific bug to fedora (on OSX was nice looking) it needs testing.
**Before** on Fedora:
**After** on Fedora
**Before** on OSX:

Fix(css): switch extra height css removed to display correctly

---

src/Charts/BaseChart.js

It was annoying me, this fix will make a console error go away. Technically just move the prop type outside the class and to do this I changed to a functional component.
**Before**
**After**
Note that difference in the `console.errors` (3rd from the bottom)

Fix: base chart prop type error fixed

---

src/Components/Toolbar.js

Solves #186 by passing `!!var` to make it always `true` or `false` value.
The error happened at the first hard refresh after turning the switch on. (Bookmarking is not working after 2 hard refreshes.)

Quickfix job expoler switch default value error

---

src/Containers/JobExplorer/JobExplorer.js

#209 
**Before**: See issue ^
**After**:

Fix: switching back from custom date in job expoler works properly

---

src/Components/TemplatesList.js
src/Containers/Clusters/Clusters.js

#183 
Adds a link to the top templates modal for the job-explorer page. Build on top of: `jo_job-explorer-list-view` branch.
Additionally fixes a console error: when `clusters` page was loaded it automatically loaded the modal window as well because of a wrong if statement and throw a `Modal needs a title or ...` error in the console. 
**Before**:
**After**:
**After clicking on `View all jobs`:**

Brumik link top templates to job expoler

---

src/Api.js

Related #232 
Convert request to `/job_explorer_options` endpoint to POST and include attributes object.
Before:
After:

Convert fetch request to /job_explorer_options to POST.

---

src/Components/TemplatesList.js

#261 
@kialam We need to pass the quick date selector field to the query for custom dates. First I wanted to change it up but it seems that in the job explorer it is used in the other way (so if a quick date is selected the start and end dates are nulled). Maybe we should consider preferring `start_date` and `end_date` fields over `quick_date_selector` field?
Otherwise, this pr fixes the issue from the templates modal.

Fixes the date query error from the template modal to job exproler

---

src/Charts/GroupedBarChart.js

Fix: Grouped bar chart now redirects to the job expoler correctly

---

src/Components/Toolbar.js
src/Components/Toolbar.test.js

do not render the date selectors if Date is not the current selection category
Fixes https://github.com/RedHatInsights/tower-analytics-frontend/issues/262
TODO:

hide date selectors if not filtering by date

---

src/Components/JobExplorerList.js
src/Components/Toolbar.js
src/Containers/JobExplorer/JobExplorer.js

This PR handles 4 TODOs from issue #238:
2. Update Pagination:
- Top of Job Explorer page should have the minimized pagination component.
- Bottom of Job Explorer page should have the default pagination component.
- Remove "Total Count" badge from the top header.
3. Update page header title to "Automation Analytics | Jobs explorer".
4. Use the compact version of the datalist component
- remove the header labels when the window size is mobile. 
- Add DataCell item labels when window size is mobile.
5. Handle long dropdown menus by setting a max-height and auto scroll.
before:
after:

Job Explorer UI Cleanup

---

src/Components/Toolbar.js

This PR handles a TODO item from issue #238:
5. Handle long dropdown menus by setting a max-height and auto-scroll.
before:
after:

Add height and hidden overflow on templates dropdown.

---

src/Components/JobExplorerList.js

Addresses column headers from #238
Before:
After:

Adjust left margin of datalist headers.

---

src/Charts/GroupedBarChart.js
src/Charts/ROITopTemplates.js
src/Utilities/Legend.js
src/Utilities/Tooltip.js

This PR handles a few Chart related UXD Audit changes.
Before: 
Verification:
Before:
Verification:
Before:
Verification:

UXD Audit: Charts

---

src/Containers/AutomationCalculator/AutomationCalculator.js
src/Containers/Clusters/Clusters.js
src/Containers/JobExplorer/JobExplorer.js
src/Containers/Notifications/Notifications.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js

I missed this error while reviewing #336. 
The page title already has a <Title h1> element in it so passing it again makes it double nesting.
**Before**
Note the error in the console.
**After**

Fixed console error about nesting h1 into h1 elements

---

src/Containers/JobExplorer/JobExplorer.js
src/Utilities/helpers.js
src/Utilities/helpers.test.js

The `queryParam` is camelCase now so we need to convert the URL parsed params to camel case also.

Fixed redirect problem: Converting url keys for queryParam to camelCase

---

src/Components/NotificationsList.js
src/Components/NotificationsList.test.js
src/Containers/Notifications/Notifications.js

This PR handles changes to the Notifications page as noted in issue #282.
PR Feedback 11/2/2020:
**Before:**
**Verification:**

Notifications Page UXD Audit Changes

---

src/Charts/BarChart.js
src/Charts/GroupedBarChart.js
src/Charts/LineChart.js
src/Components/TemplatesList.js
src/Containers/AutomationCalculator/AutomationCalculator.js

Found a bug where the redirects where an array is required just sent a single value then the JobExplorer would not load data.
This PR updates all the redirects so they all work as expected. 
In addition, converted snake_case to camelCase for the redirect object keys.

Fixing redirects

---

.travis/custom_release.sh
README.md

This change will push to all beta environments from devel.     This supports a faster beta feedback cycle but makes production-beta more unstable.   Users can always go to the non-beta production site if they want a stable version.
Please discuss pushing to all betas at the same time from devel.   Point out any problems like the left nav needing matching PRs.

Push to all the betas from devel

---

.eslintrc.yml

Since we have a convention of using snake case to match the attributes from the API turn off camel case checking.

Disable camel case check

---

config/setupTests.js
src/App.test.js

Removed the `App.test` mock of `insights`. We have it globaly set up. Let this test to use it as well.

Tests: Updated the App tests to use the global insights object

---

cypress.json
cypress/integration/AutomationCalculator.spec.js
cypress/integration/Dashboard.spec.js
cypress/integration/Global.spec.js
cypress/integration/Notifications.spec.js
cypress/integration/OrganizationStatistics.spec.js
cypress/integration/constants.js
cypress/support/commands.js

For these changes we need to change the pipeline here: https://github.com/RedHatInsights/analytics-pipeline
Renamed:
* `CLOUD_PASSWORD --> PASSWORD` 
* `CLOUD_USERNAME --> USERNAME` 
* `CLOUD_BASE_URL --> BASE_URL`
Also, the base URL is now set in the `cypress.json` making running server checks available.  The `baseURL` is a standard convention in cypress and it is best practice to have it set up. Allows using visit, without specifying the base URL part all the time.
So instead of: `cy.visit('https://localhost:8000/index')` we can use just `cy.visit('/index')`.
Added `viewport` to the config file. This sets the default viewport for all tests. If it is needed it can be overwritten with `cy.viewport(x, y)` from withing the tests.
In cypress, waits are …

Cypress testing: Changed env variable for baseURL

---

package-lock.json
package.json
src/Containers/JobExplorer/JobExplorer.js
src/Utilities/useApi.js
src/Utilities/useApi.test.js

@kialam It was a long time ago that we speak about this, but I had to made fetching research, and while at it I come up with this solution. (Now I understand why there were `ignore` at API fetching)
I think this hook could simplify fetching API. I can fetch one endpoint or multiple (`Promise.all`). It accepts a postprocessing function, allowing it to remap or modify data from API. It is also preventing memory leaks when the component is unmounted before API is fetched.
Returns and object with the following keys: 
* (bool) isLoading
* (string) errror - null if no error
* (bool) isSuccess - loaded without error --> this variable replaces the `!isLoading && !error`, making the code more readable.
* (object) data - the loaded data from the API
**Note**: Needed to update `JobExplorerList` …

Added useApi hook to simplify fetching

---

src/Utilities/useQueryParams.js

This PR addresses a bug in prod on the Notifications page that causes an empty query string to be sent to the Notifications endpoint on the selection of the 'View All' filter. 
**Before:**
**After:**
Jira Issue: https://issues.redhat.com/browse/AA-238

'View All' Bugfix on Notifications page

---

src/Containers/AutomationCalculator/AutomationCalculator.js
src/Containers/AutomationCalculator/TopTemplates.js

The switches are not icons as they used to be. Will ot be fine with a normal switch component or should we find the original switch icons?

Added switches back to the top templates on the roi page

---

src/Components/Toolbar/ToolbarFilterItem.js

This PR fixes a bug that causes filter dropdowns to go off-page when there are several options. 
**Before**
**Fixed**

Expanded filter dropdown bugfix

---

src/Containers/JobExplorer/JobExplorer.js
src/Utilities/useQueryParams.js

It was cause by the fact that the initial query param was updated at 
every rerender from the search. Therefore the clear all button reseted 
the state to the CURRENT state.

Fixed clear filter button on job explorer

---

src/Charts/GroupedBarChart.js

The redirect date was invalidly formatted, this pr fixes it.

Fixed date formatting from the Grouped Bar chart to the Job exploler

---

src/Containers/AutomationCalculator/AutomationCalculator.js
src/Containers/AutomationCalculator/TopTemplates.js
src/Containers/AutomationCalculator/TopTemplates.test.js

Spoke with @trahman73 on this and the fix is to:
1. Dynamiclaly show in the UI on the right side Templates list column the sort by details:
2. Include all the sort by attributes/values returned by the API in the popover like so:

AA-352 Improve Sort UX in Automation Calculator

---

src/Api.js
src/Containers/Clusters/Clusters.js
src/Containers/JobExplorer/JobExplorer.js
src/Containers/Notifications/Notifications.js
src/Utilities/useApi.js

this fixes https://issues.redhat.com/browse/AA-353
For whatever reason, the useApi hook did not seem to be successfully gating requests until they were finished logging in.  I also found a number of places (that I guess have not been converted to this useApi hook yet).  So here is an attempt at a simple and consistent solution for gating api requests to make sure they are logged in first.
This pr does two things:
- removes `window.insights.chrome.auth.getUser()` across the app
- wraps fetch calls in api.js (which seemed to be the centralized place that stores alll api requests) in a simple wrapper which calls `window.insights.chrome.auth.getUser()`, waits for a response, and then returns fetch

utilize centralized authenticated fetch api helper

---

src/Containers/OrganizationStatistics/OrganizationStatistics.js

There's a lot of noise in this PR as I re-ordered the list of params for each of the charts so they're ordered alphabetically for ease of readability, but the main fix for this bug is to [change out the `attribute` param in `jobRunsByOrgParams ` from `host_count` to `total_count`](https://github.com/RedHatInsights/tower-analytics-frontend/commit/9d269f3fec018eb31f0148aaca73da7959b90c40).

Fix AA-429 pie chart values

---

Makefile

After discussing my thoughts around documenting the fully local setup with @benthomasson, he had the idea that trying to automate it may help make this stuff more impervious to being out of date.  So here's my very rudimentary attempt at doing that.  It definitely needs beefing up before it is useful and ready to merge, I think.
Basically, it is a new phony make target which starts and attaches to a tmux session which contains all the main pieces for a fully local UI dev setup:
- cloud-services-config for custom side nav
- frontend running webpack dev (i.e. always updating the bundle as changes are made to the frontend src)
- backend ran using headless (i.e. no ui cotainer) make ui target
- insights-proxy running using the fast-api config to connect all these pieces.
Iteration 1 looks …

scripted tmux config for fully local ui dev setup

---

src/Components/ModalContents.js

This will allow is to correctly display the last 5 jobs.
Issue filed [here](https://issues.redhat.com/browse/AA-152?focusedCommentId=16003811&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16003811).

Clusters modal: change sort order to descending instead of ascending

---

src/Charts/GroupedBarChart/GroupedBarChart.js
src/Charts/PieChart.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js

This updates the number of labeled ticks on the x axis of the org stats chart.  For grouped bar I go to every 2 for month view, and every 4 for 2 month view.
I also removed timeFrame data prop to clean things up for consistency across all the different charts (unused in pie charts, and we were just finding the length of the data on line/bar).

update chart axis ticks:

---

.github/workflows/main.yml
package.json
src/Charts/GroupedBarChart/GroupedBarChart.js
src/Charts/PieChart.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js
src/Utilities/Legend.js

The API now provides a legend field in the meta, where the `Others` has the correct number before it. This PR making use of this extra information, displaying the correct number of others in the legend.
**Additionally:**
- The `name` prop could not be used for colors coding, since the `X Other` string could be different in the charts, so the `id` is used instead
- The grouped bar chart groups used the `name` as the domain for ordering, but since the `name` is now different in the series (since in every series there can be a different amount of `Others`) the `id` is used for specifying the subdomain bandwidth.
**CSS Update:**
Played around with the CSS in the legend to make the count align nicely and consistently to the right. 
**Before**:
**After**:

Updated orgs page legend from the api

---

src/Api.js
src/Containers/AutomationCalculator/AutomationCalculator.js
src/Containers/AutomationCalculator/AutomationCalculator.test.js
src/Containers/Clusters/Clusters.js
src/Containers/JobExplorer/JobExplorer.js
src/Containers/JobExplorer/JobExplorer.test.js
src/Containers/Notifications/Notifications.js
src/Containers/Notifications/Notifications.test.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js
src/Containers/OrganizationStatistics/OrganizationStatistics.test.js
src/Utilities/constants.js
src/Utilities/tests/helpers.js

Added `AlertMessage` component that uses patternfly Alert component, this component can be used/enhanced further to be used as common component to display other notifications to user on screen.
https://issues.redhat.com/browse/AA-322
@benthomasson pls review first cut, hopefully i am on right track.
before
User without RBAC acces to Automation Calculator screen
User with RBAC acces to Automation Calculator screen
after
User without RBAC acces to Automation Calculator screen
User with RBAC acces to Automation Calculator screen

First cut of changes to display RBAC error message and stop loading of other elements on the screen when user does not have access to the screen.

---

src/Components/Breadcrumbs.js
src/Components/Breadcrumbs.test.js
src/Utilities/getBaseName.js
src/entry-dev.js
src/entry.js

as a prerequisite of my savings planner add and @h-kataria's savings planner detail work, this adds support for breadcrumbs based on the pf-core breadcrumb components.
I initially implemented this using the crc breadcrumb component, but after seeing deprecation messages when writing the tests, I changed to using the pf-core components.  Since the core components utilize href, I followed the entry pattern I found in the codebase to grab the base path using the utility function made for it.
As part of this, it seemed like "window.location.pathname" felt like it should be the default param for that rather than passed across the app so I made that small tweak.

add breadcrumbs

---

src/Api.js
src/Components/Popover.js
src/Components/Toolbar/Toolbar.js
src/Containers/SavingsPlanner/Add/index.js
src/Containers/SavingsPlanner/SavingsPlanner.js
src/Containers/SavingsPlanner/Shared/Details.js
src/Containers/SavingsPlanner/Shared/Form.js
src/Containers/SavingsPlanner/Shared/Tasks.js
src/Containers/SavingsPlanner/Shared/Templates.js
src/Routes.js
src/Utilities/useForm.js
src/paths.js

This PR adds the Savings Planner add flow.
Currently, the pr:
- Adds “Add plan” button to Savings Planner card view to get to add screen
- Adds breadcrumb link back to savings planner list
- Adds in wizard component with hash-linkable steps (the hash linking will be needed for edit view)
- Adds in grid-based form from PF
- Some fields needed the ? Help popover link in the label of the field…I pulled in this component from awx.
- Adds in drag-orderable task adding list
- Task add input allows both enter key-down and clicking “+” button to add
- Clicking the “x” in the remove will remove the task from the list.  I talked with Taufique and we decided against any sort of confirmation dialog for this particular interaction.
- Adds in radio single-select template list
- Note, this is a simple, …

savings planner add flow

---

src/Components/Toolbar/Groups/ToolbarInput/Select.js
src/Components/Toolbar/Groups/ToolbarInput/index.js

I got it wrong how the `PropTypes.arrayOf()` works. My bad. This commit fixes the warnings that it was throwing when using the toolbar.

Fix: Toolbar props accepts number or string array as it should

---

src/Api.js
src/Components/AlertModal/AlertModal.js
src/Components/AlertModal/AlertModal.test.js
src/Components/AlertModal/index.js
src/Components/CardActionsRow.js
src/Components/DeleteButton/DeleteButton.js
src/Components/DeleteButton/DeleteButton.test.js
src/Components/DeleteButton/index.js
src/Components/ErrorDetail/ErrorDetail.js
src/Components/ErrorDetail/ErrorDetail.test.js
src/Components/ErrorDetail/getErrorMessage.js
src/Components/ErrorDetail/getErrorMessage.test.js
src/Components/ErrorDetail/index.js
src/Components/Toolbar/ToolbarDeleteButton.js
src/Components/Toolbar/ToolbarDeleteButton.test.js
src/Containers/SavingsPlanner/DetailsTab.js
src/Containers/SavingsPlanner/PlanCard.js
src/Containers/SavingsPlanner/SavingsPlanner.js
src/Utilities/getRelatedResouceDeleteDetails.test.js
src/Utilities/getRelatedResourceDeleteDetails.js
src/Utilities/useIsMounted.js
src/Utilities/useRequest.js
src/Utilities/useSelected.js
src/Utilities/useSelected.test.js

- This commit adds a delete button in toolbar if user has RBAC Access. Clicking on delete button will open up a confirmation modal with  All selected plan names displayed in modal. Upon confirmation, records will be deleted and list view will be refreshed to show a list of plans.
- Added Delete button on the details tab with same confirmation modal, upon confirmation, record will be deleted and user will be redirected back to refreshed list view screen
List screen
Details screen

Added Delete button on List and Details view

---

src/Components/Toolbar/ToolbarDeleteButton.js

@jlmitch5 it seems during a code cleanup process, I ended up removing a `<div>` element around the button.
The current Tooltip component looks at its child to see if that is disabled. If so, the tooltip is not displayed. In order to always show a tooltip, we need to add a div tag around it.

Fixed to display tooltips on disabled `Delete` button on list

---

src/Components/Toolbar/Toolbar.js
src/Containers/SavingsPlanner/PlanCard.js
src/Containers/SavingsPlanner/Shared/Form.js
src/Containers/SavingsPlanner/Shared/Templates.js

This PR:
- makes kebab actions of "edit" and "link template" on the plan cards work
- allows configurable hiding of certain subsections of the toolbar by passing props
- updates the plan add/edit link template list to using the paginated, react-table composable pf components.
NOTE:
- only the name column is shown currently.  I talked with @AparnaKarve and opened an issue to track adding the type information.  also to add sorting for template name and type.
- filtering by status also seems a little messed up, commented that in the issue as well
- currently if you try to "clear" a template to "no template selected", it will not work.  @AparnaKarve is working on allowing -2 to be passed for no template on both POST and PUT.  I'm opening a PR to remove that conditional from the usePlanData …

Link template list

---

src/Containers/SavingsPlanner/Add/index.js
src/Containers/SavingsPlanner/DetailsTab.js
src/Containers/SavingsPlanner/DetailsTab.test.js
src/Containers/SavingsPlanner/Edit/index.js
src/Containers/SavingsPlanner/PlanCard.js
src/Containers/SavingsPlanner/SavingsPlan.js
src/Containers/SavingsPlanner/SavingsPlan.test.js
src/Containers/SavingsPlanner/SavingsPlanner.js
src/Containers/SavingsPlanner/Shared/Tasks.test.js
src/Utilities/__fixtures__/readPlansOptions.js

related: https://issues.redhat.com/browse/AA-544
view only users see a list of savings plans (if any):
editor or admin users see Add and Delete buttons as well as kebab menu on the cards for Edit and Link Template workflows:
This PR implements a _basic_ RBAC UX workflow based on the permissions returned from the `plan_options` endpoint. There are no additional required API calls made to determine RBAC, so this is basically setting a boolean and showing/hiding/redirecting based on that boolean.

AA-544 add basic RBAC for add, edit, delete Savings Plan.

---

src/Containers/SavingsPlanner/Shared/usePlanData.js

The API will support passing -2 as the official indication that "no template is added to this plan".  This allows us to fix the corner case where the user creates a plan with a template linked and later wants to remove that template.

remove -2 delete template savings plan POST/PUT payload formatter

---

src/Components/ErrorDetail/ErrorDetail.js
src/Components/Toolbar/Groups/ToolbarInput/Text.js
src/Containers/SavingsPlanner/Shared/Form/Steps/Details/index.js
src/Containers/SavingsPlanner/Shared/usePlanData.js

Just a couple of tiny fixes:
- sets a max height for the category dropdown
- pass 1 if no host number is specified, i.e. the default is deleted from the field
- hide details section of error modal if there are none passed by the API for us to display.
- make onKeyDown enter work for the name search.

Savings planner QE audit fixes

---

src/Containers/AutomationCalculator/AutomationCalculator.js
src/Containers/AutomationCalculator/TopTemplates.js

The Grid components by default works with 12 spans, where the closest looking division was 9:3 (which is also used on the Statistics tab at savings planner) so the right column is slightly smaller than was before.
The TopTemplates component was made to span until the end of the page so the user can see more than 1 template at once instead of lots of gray empty space. The left column made it match in height so it still looks consistent. 
Additional gains: easier to convert the page to a more responsive "mobile-friendly" version if we wish so (I did not looked into it but hoped it would work out of the box).
**Before:**
**After:**

Converted custom Main component styling to grid and stack

---

.dockerignore
.travis.yml
Dockerfile
package.json

After quick consult with @benthomasson :
* Travis is duplicate on PRs, now it runs only on the branches we need to deploy (devel, prod-stable)
* Removing the docker initialization from the repo, it seems like nobody is using it. If somebody complains we can add it back :) (fun times)

Ci clean 2

---

src/Api.js

The trailing slash is failing the call.  This is reproducible with `curl`.  Something to do with 3scale config.

Feature flag proxy url updated

---

config/dev.webpack.config.js
config/prod.webpack.config.js
package.json
src/App.js
src/store/index.js

With the new chrome nav changes getting deployed to all environments (prod-beta Wednesday, July 21st and prod-stable Monday, July 26th), we can now safely enable chrome 2 navigation for this application.
It will enable the following:
- Client-side routing when navigating between chrome 2 apps
- Consuming chrome 2 API via `useChrome` hook
- trough this API all future features will be accessible
- global error boundary to prevent apps from crashing the whole UI
**This PR depends on CSC prs! It will not work without them, we have to make sure we merge them simultaneously.**
- ci/qa/qaproduath/stage-beta envs: https://github.com/RedHatInsights/cloud-services-config/pull/780
- ci-stable: https://github.com/RedHatInsights/cloud-services-config/pull/781
- qa/stage/qaproduath-stable: …

Enable chrome 2

---

src/Utilities/useRequest.js

Note: use request could use one state so we change only one state when setting values instead of changing multiple ones.
Changing multiple ones at the same time can potentially make react rerender multiple times, which is not an issue but it is not ideal.
The issue what is fixed:
When loading data the loading screen appears above the data and not instead of it. This is caused by the new useRequest returning `isSuccess` and `isLoading` alongside each other.
This is affecting all of our pages.

Updated use request so it does not return success and loading

---

src/Components/ModalContents.js
src/Containers/AutomationCalculator/AutomationCalculator.js
src/Containers/AutomationCalculator/AutomationCalculator.test.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js
src/Containers/SavingsPlanner/Details/DetailsTab/index.js
src/Containers/SavingsPlanner/List/ListItem/index.js

params need to be prefixed by namespace when building a link to redirect to job explorer from various screens.
@jlmitch5 please review, this should fix the issue you saw with the link to template from Savings-planner list/details view

Added namespace prefix on params in url.

---

src/Api/api.ts
src/Components/EmptyState.js
src/Components/ModalContents.js
src/Containers/AutomationCalculator/AutomationCalculator.js
src/Containers/Clusters/Clusters.js
src/Containers/Clusters/Clusters.test.js
src/Containers/JobExplorer/JobExplorer.js
src/Containers/Notifications/Notifications.js
src/Containers/OrganizationStatistics/OrganizationStatistics.js
src/Containers/SavingsPlanner/Add/index.js
src/Containers/SavingsPlanner/Details/Details.js
src/Containers/SavingsPlanner/Details/DetailsTab/index.js
src/Containers/SavingsPlanner/Details/DetailsTab/index.test.js
src/Containers/SavingsPlanner/Details/StatisticsTab/index.test.js
src/Containers/SavingsPlanner/Details/StatisticsTab/index.tsx
src/Containers/SavingsPlanner/Edit/index.js
src/Containers/SavingsPlanner/List/List.js
src/Containers/SavingsPlanner/Shared/Form/Steps/Details/index.js
src/Containers/SavingsPlanner/Shared/Form/Steps/Templates/index.js
src/Containers/SavingsPlanner/Shared/Form/index.js
src/Utilities/getRelatedResouceDeleteDetails.test.js
src/Utilities/getRelatedResourceDeleteDetails.js
src/__tests__/fixtures/index.js
src/__tests__/fixtures/readPlan.js

* Make the `readApi` params into a simple object instead of nesting, it makes TS much easier in the future
* Fixed the job explorer bookmarking (it was using duplicate bookmarking which worked weird)
* Unified the useRequest usage, removed unnecessary wrapping where was not needed.
* Corrected the default variables passed to the useRequest
* Unified the `preflight` usage
* Added the `Not authorized` to the `EmptyState` (which is handling all possible preflight errors, probably we should rename)
* **Fixed** the infinite rbac call on the details page

useRequest usage unification

---

src/Containers/AutomationCalculator/AutomationCalculator.js

Cannot make screenshots while it is a loading screen. 
**Before**: When api was loading or errored out the `No Data` screen was still showing.
**After**: The `No Data` is showed only when the request to API is successful and there is really no data returned from the API

Fix: don't show NoData while loading the ROI calculator

---

src/Containers/SavingsPlanner/Details/StatisticsTab/index.tsx
src/Containers/SavingsPlanner/Shared/Form/Steps/Details/index.js
src/Containers/SavingsPlanner/Shared/Form/Steps/Details/index.test.js
src/Containers/SavingsPlanner/Shared/Form/Steps/Templates/index.js

Old Savings Planner looked for `options.data.{property_here}` but the new output is instead `options.{property_here}`. Also updated default params for Template Selection stage of Savings Planner.

Update Savings Planner to handle new API outputs

---

cypress/integration/AutomationCalculator.spec.js
cypress/integration/Dashboard.spec.js
cypress/integration/JobExplorer.spec.js
cypress/integration/OrganizationStatistics.spec.js
cypress/integration/SavingsPlanner.spec.js

This PR adds some basic tests for query parameter storage in the URL. There is one outstanding issue at the moment, which is whether or not jobtype should be retained there since it currently is not.

AA-145 - Store Query Parameters in url

---

src/Utilities/qs.js
src/Utilities/qs.test.js

Fixes: AA-667
In addition it fixes also AA-678
**Before:**
- The default params never got into the url, even if only a subset was selected. This prevented bookmarking combinations which were using the default params, but weren't the same. 
- Error when changing pagination in the console
**After:**
- Default params still not added to the url, as long as the filter is not changed. After any change the params will be saved into the URL
- No errors when changing pagination

Fix: the default params were never in the URL, now they are always

---

src/Components/Toolbar/Groups/QuickDateGroup.tsx
src/Components/Toolbar/Toolbar.tsx
src/Components/Toolbar/constants.ts
src/Containers/Reports/Details/Report.tsx
src/Containers/Reports/Shared/schemas/affected_hosts_by_playbook.ts
src/Containers/Reports/Shared/schemas/changes_made.ts
src/Containers/Reports/Shared/schemas/playbook_run_rate.ts
src/Containers/Reports/Shared/types.ts
src/Utilities/useQueryParams.js

* Chart x axis labels are not too helpful when setting to year (showing 01/01 for all ticks)
* possible solutions: display full date always or change the date depending on the granularity (hard mode)
* Quick date range from API does not change with the granularity which is then weird
* Granularity could go next to the date selector instead to the category drop down. Waiting for the #555 PR to be merged, so we don't cause accidental bugs.
(Done) TODO: 
- Granularity to the left of the date selector
- Change the chart axis depending on the granularity

Added granularity to the report charts

---

src/Containers/OrganizationStatistics/OrganizationStatistics.js
src/Containers/Reports/Details/Details.tsx
src/Containers/Reports/List/List.js
src/Containers/Reports/List/ListItem/index.js
src/Containers/Reports/Shared/schemas/affectedHostsByPlaybook.ts
src/Containers/Reports/Shared/schemas/changesMade.ts
src/Containers/Reports/Shared/schemas/hostsByOrganizations.ts
src/Containers/Reports/Shared/schemas/index.ts
src/Containers/Reports/Shared/schemas/jobsTasksByOrganization.ts
src/Containers/Reports/Shared/schemas/playbookRunRate.ts
src/Containers/Reports/Shared/types.ts
src/Containers/Reports/index.tsx

**Before**:
- Opening a report put a number into the url:
- for example: `.../reports/4`
**After**:
- Reports have unique slugs for displaying in the URL
- example: `.../reports/hosts_by_organization`

[Waiting for PR-570] Add slugs to reports in url instead of IDs

---

src/Components/Toolbar/Groups/SettingsPanel.tsx

Changed the tooltip to a popover in the settings toolbar on the Job Explorer page.
Before:
After:

Make tooltip into popover in the settings toolbar for Job Explorer page

---

src/Utilities/qs.js

`if (!newVal && newVal !== '')` was evaluating as true when offset value was 0 in the querystring and in return was setting offset value to 'undefined' causing pagination to show NaN on the screen.
before
after
This issue only happened when offset value was 0 in url

Extended condition to also check if value is not 0

---

src/Containers/OrganizationStatistics/OrganizationStatistics.js

Fixes typo in deprecation warning on Organization Statistics page

---

src/App.test.js
src/Components/Error404.tsx
src/Routes.js

> Currently we are redirecting to the clusters page if a top level link is not found in our routes. We should display the 404 page instead as this will be confusing to users especially if we remove a page (for example the orgs page)

404 page for root urls

---

src/Components/Toolbar/Toolbar.tsx

Made the filterable toolbar responsive. The filter icon now only appears when window is minimized to a specific width (previously, it served no function). 
Before:
After:
After (when filter icon is clicked):

Make Filterable Toolbar Responsive

---

src/Components/Toolbar/Groups/QuickDateGroup.tsx

The date selectors were not displaying when "Custom" was selected in Automation Calculator.
Before: 
After:

Fix date selector

---

src/Containers/SavingsPlanner/Shared/Form/index.js

- Display an error message when trying to save a Savings Plan with the name that exists.
https://issues.redhat.com/browse/AA-607
before
after

Fixed to display the error message

---

src/Components/Toolbar/DownloadPdfButton.js

Fixed the small activation space on the download PDF button.
Before (only activated tooltip in the middle of the icon):
After (now activates in the entire button area):

Fixed tooltip activation space

---

src/Api/types.ts
src/Components/Toolbar/DownloadPdfButton.js
src/Containers/Reports/Details/Components/ReportCard.tsx
src/Containers/Reports/Shared/schemas/affectedHostsByPlaybook.ts
src/Containers/Reports/Shared/schemas/changesMade.ts
src/Containers/Reports/Shared/schemas/hostsByOrganizations.ts
src/Containers/Reports/Shared/schemas/jobsTasksByOrganization.ts
src/Containers/Reports/Shared/schemas/moduleUsageByJobTemplate.ts
src/Containers/Reports/Shared/schemas/moduleUsageByTask.ts
src/Containers/Reports/Shared/schemas/moduleUsagebyOrganization.ts
src/Containers/Reports/Shared/schemas/mostUsedModules.ts
src/Containers/Reports/Shared/schemas/playbookRunRate.ts
src/Containers/Reports/Shared/schemas/templatesExplorer.ts
src/Containers/Reports/Shared/types.ts

Passing qsparams and other params to pdf generation & fastapi endpoint which queries data directly, rather than passing the data itself
goes with:
https://gitlab.cee.redhat.com/automation-analytics/automation-analytics-backend/-/merge_requests/268
https://gitlab.cee.redhat.com/automation-analytics/pdf-generator/-/merge_requests/15

AA-802 passing params to fastapi to generate data for PDF

---

src/Containers/Reports/Shared/schemas/templatesExplorer.ts

Matched the wording in the chart tooltips to the wording in the sort category dropdown.
Jira issue: https://issues.redhat.com/browse/AA-854 
Before:
After:

Tooltip fix to match dropdown label

---

src/Components/Toolbar/DownloadPdfButton.js

showExtraRows was passing the opposite value to the back end, causing the wrong pdf report to download from UI.

Fixed boolean in showExtraRows for PDF download

---

src/Containers/Reports/Details/index.tsx
src/Containers/Reports/List/ListItem/index.tsx
src/Containers/Reports/Shared/constants.ts
src/Containers/Reports/Shared/schemas/affectedHostsByPlaybook.ts
src/Containers/Reports/Shared/schemas/automationCalculator.ts
src/Containers/Reports/Shared/schemas/changesMade.ts
src/Containers/Reports/Shared/schemas/hostsByOrganizations.ts
src/Containers/Reports/Shared/schemas/jobsTasksByOrganization.ts
src/Containers/Reports/Shared/schemas/moduleUsageByJobTemplate.ts
src/Containers/Reports/Shared/schemas/moduleUsageByOrganization.ts
src/Containers/Reports/Shared/schemas/moduleUsageByTask.ts
src/Containers/Reports/Shared/schemas/mostUsedModules.ts
src/Containers/Reports/Shared/schemas/playbookRunRate.ts
src/Containers/Reports/Shared/schemas/templatesExplorer.ts
src/Containers/Reports/Shared/types.ts

Added tags to show on the card view and details view of all reports, with a tooltip containing the description for the tag. 
Jira issue: https://issues.redhat.com/browse/AA-888 
Before: 
After:

Display tags with descriptions on all reports

---

src/Components/Toolbar/DownloadPdfButton.js

Changed the export PDF radio option for when the data set is larger than 100 items. This change makes it more consistent with the information that will be displayed on the PDF.
Before:
After:

Export modal top 100 message edit

---

src/Containers/Reports/Layouts/AutomationCalculator/TemplatesTable/ExplandedRowContents.tsx
src/Containers/Reports/Layouts/AutomationCalculator/TemplatesTable/Row.tsx

Note the 2 decimal places in the Template productivity column and the `s` in the expanded row elasped data field.

[AA-910] Updated the roi report table displayed values

---

src/Components/Toolbar/DownloadPdfButton.tsx
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.js
src/Containers/Reports/Layouts/Standard/ReportCard.tsx

Removed all radio options in pdf download modal when the total number of items is less than or equal to currently displayed items. Instead, text will be displayed reflecting that this report would show all available data.
Jira issue: https://issues.redhat.com/browse/AA-913

Removed radio options in PDF download modal

---

src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.js
src/Containers/Reports/Layouts/Standard/ReportCard.tsx
src/Containers/Reports/Shared/schemas/aa21OnboardingReport.ts
src/Containers/Reports/Shared/schemas/affectedHostsByPlaybook.ts
src/Containers/Reports/Shared/schemas/automationCalculator.ts
src/Containers/Reports/Shared/schemas/changesMade.ts
src/Containers/Reports/Shared/schemas/hostsByOrganizations.ts
src/Containers/Reports/Shared/schemas/jobsTasksByOrganization.ts
src/Containers/Reports/Shared/schemas/moduleUsageByJobTemplate.ts
src/Containers/Reports/Shared/schemas/moduleUsageByOrganization.ts
src/Containers/Reports/Shared/schemas/moduleUsageByTask.ts
src/Containers/Reports/Shared/schemas/mostUsedModules.ts
src/Containers/Reports/Shared/schemas/playbookRunRate.ts
src/Containers/Reports/Shared/schemas/templatesExplorer.ts
src/Containers/Reports/Shared/types.ts

*  Fix the types and mutation in the reports card 
*  Updated the schema to allow reorder-able columns in the table 
No UI/behavioural changes

[AA-926] Make report tables reorder-able

---

src/Containers/Reports/Shared/schemas/aa21OnboardingReport.ts
src/Containers/Reports/Shared/schemas/affectedHostsByPlaybook.ts
src/Containers/Reports/Shared/schemas/changesMade.ts
src/Containers/Reports/Shared/schemas/hostsByOrganizations.ts
src/Containers/Reports/Shared/schemas/jobsTasksByOrganization.ts
src/Containers/Reports/Shared/schemas/moduleUsageByJobTemplate.ts
src/Containers/Reports/Shared/schemas/moduleUsageByOrganization.ts
src/Containers/Reports/Shared/schemas/moduleUsageByTask.ts
src/Containers/Reports/Shared/schemas/mostUsedModules.ts
src/Containers/Reports/Shared/schemas/playbookRunRate.ts

Fixed legend to truncate properly when values are in uppercase letters/wide characters.
Jira issue: https://issues.redhat.com/browse/AA-936
Related to MR: https://gitlab.cee.redhat.com/automation-analytics/pdf-generator/-/merge_requests/66
Before: 
After:

Fixed legend truncation

---

src/Utilities/constants.ts

Changed the item limit on the automation calculator report from 25 to 6 (the standard number of items displayed on all other reports).
Jira issue: https://issues.redhat.com/browse/AA-931
Before: 
After:

Changed item limit

---

package.json

Currently, the travis ci already have lint and test stages. The third stage `Deploy` is running again the lint and test. That is duplicating the work and slowing down the PR ci turn around time.
https://github.com/RedHatInsights/tower-analytics-frontend/blob/main/.travis.yml#L18-L23
```  
include:
- stage: Lint
script: npm run lint
- stage: Test
script: npm run test
- stage: Deploy
script: npm run deploy && curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/bootstrap.sh | bash -s
```

removing duplicated lint and test in deploy stage

---

src/Api/types.ts
src/Components/Chart/index.tsx
src/Components/Toolbar/DownloadPdfButton.tsx
src/Containers/Clusters/Clusters.test.js
src/Containers/Notifications/Notifications.tsx
src/Containers/SavingsPlanner/Shared/Form/Steps/Templates/index.test.js
src/QueryParams/Context.js
src/QueryParams/Context.ts
src/QueryParams/Provider.tsx
src/QueryParams/__tests__/Context.test.js
src/QueryParams/__tests__/Provider.test.js
src/QueryParams/__tests__/helpers.test.js
src/QueryParams/__tests__/index.test.js
src/QueryParams/__tests__/redirectWithQueryParams.test.js
src/QueryParams/__tests__/useQueryParams.test.js
src/QueryParams/__tests__/useRedirect.test.js
src/QueryParams/helpers.ts
src/QueryParams/index.ts
src/QueryParams/redirectWithQueryParams.ts
src/QueryParams/types.ts
src/QueryParams/useQueryParams.js
src/QueryParams/useReadQueryParams.ts
src/QueryParams/useRedirect.ts
src/Utilities/useAsyncActionQueue.ts

* Make all charts toggles (hide show in legend) to be present in the URL in the `settings` namespace by default, allowing to override it with a prop.
* To make it work I had to:
* make the useQueryParam hook to work with mutliple components for the same namespace. 
* that needed and update to the QueryParam context, saving the initial values (and removing them) in the global state so all the different hooks can add and remove them
* While doing it I applied to the changed files a minimal TS update.
@jlmitch5 @h-kataria 
I consider this PR done, I won't have time to do the PDF generator part of the transcending legend before Christmas, but it will be relatively fast and easy after this, to do in January.

Transcende legend

---

src/QueryParams/useQueryParams.js

Fixes: https://issues.redhat.com/browse/AA-968
Go to Automation Calculator report -> click on last page in pagination -> set some filters
Before:
After:

AA986 - Reset pagination when setting filter 

---

src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
src/Containers/Reports/Shared/schemas/automationCalculator.ts

Fixed to update label on Y axis to match the sort by field in toolbar. Tooltip labels are updated to show "Savings for X: $123,00.00" instead of “Savings per template”. amount value is formatted as currency, with the correct currency symbol and number of decimal places.
https://issues.redhat.com/browse/AA-932
before
after

Visualization updates to ROI chart

---

src/QueryParams/__tests__/useQueryParams.test.js

Follow-up to https://github.com/RedHatInsights/tower-analytics-frontend/pull/723 change

Add test that offset is reset when a filter in toolbar is set

---

src/Containers/AutomationCalculator/AutomationCalculator.js
src/Containers/AutomationCalculator/AutomationCalculator.test.js
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx

UI changes to adjust old Automation Calculator screen.
Fixed tooltips on new ROI report page, that somehow got lost with maybe Zita's PR merge with ROI visual changes
https://issues.redhat.com/browse/AA-958

Used data in meta['legend'] instead of items from API response

---

src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
src/Containers/Reports/Layouts/AutomationCalculator/TemplatesTable/Row.tsx
src/Containers/Reports/Layouts/AutomationCalculator/TemplatesTable/index.tsx
src/Containers/Reports/Layouts/Standard/Table/index.tsx
src/Utilities/percentageFormatter.ts
src/Utilities/timeFormatter.ts

Replaces https://github.com/RedHatInsights/tower-analytics-frontend/pull/720
Fixes: https://issues.redhat.com/browse/AA-935
- Adding units to sortable column
After:
- Adding empty state when all data is hidden
Before:
After:
- Adding sort to sortable column
Before:
After:

AA935 ROI report table fixes

---

src/Components/ApiStatus/ApiStatusWrapper.tsx
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
src/Containers/Reports/Layouts/AutomationCalculator/CalculationCost.tsx
src/Containers/Reports/Layouts/AutomationCalculator/TemplatesTable/Row.tsx
src/Containers/Reports/Layouts/AutomationCalculator/TemplatesTable/index.tsx
src/Containers/Reports/Layouts/AutomationCalculator/TotalSavings.tsx

Fixes https://issues.redhat.com/browse/AA-986
- use spinner for components that are rerendred
- inputs have focus when used
- spinners are the same size as chart and $ sum - not posssible to do for the table
Before:
After:

ROI report loading fixes

---

src/Containers/Clusters/Clusters.test.js
src/Containers/SavingsPlanner/Shared/Form/Steps/Templates/index.test.js
src/QueryParams/Context.ts
src/QueryParams/Provider.tsx
src/QueryParams/types.ts
src/QueryParams/useQueryParams.js
src/QueryParams/useReadQueryParams.ts

initialParams was stepping on initial default params, when clicking on links fast before previously clicked link screen was loaded.
https://issues.redhat.com/browse/AA-1013

Removed initialParams, addInitialParams, removeInitialParams and their references

---

src/Containers/SavingsPlanner/Details/StatisticsTab/TotalSavings/index.tsx
src/Containers/SavingsPlanner/Details/StatisticsTab/index.tsx

Updated colors used for money-based savings in savings planner to be more consistent with ROI report and patternfly guidelines. 
Before: 
After:

Update savings planner colors

---

package.json

Pacakge Json
Before proceeding, we’ll need to turn off the cache for jest. To do this, add the following line to your package.json, or update your existing jest entry to match the following.
https://consoledot.pages.redhat.com/docs/dev/getting-started/frontend-migration.html#_pr_check_and_build_deploy

AA-1015-Pipeline-upgrades

---

src/Api/api.ts
src/Api/methods.ts
src/Api/types.ts
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.test.js
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
src/Containers/Reports/Layouts/AutomationCalculator/CalculationCost.tsx
src/Containers/Reports/Layouts/AutomationCalculator/TemplatesTable/Row.tsx
src/Containers/Reports/Layouts/AutomationCalculator/TemplatesTable/index.tsx
src/QueryParams/__tests__/useQueryParams.test.js
src/QueryParams/useQueryParams.js

Fixes https://issues.redhat.com/browse/AA-1007
Fixes https://issues.redhat.com/browse/AA-987 as well
- Values from calculation and table are no longer saved in params but to DB.
- Not using `useRequest` for saving the values to DB allows me not to reload components. But it goes against consistency of the code so it's up to discussion :)
- rbac check - a readonly user cannot edit inputs. See screenshot at the end
- moving hide/show logic from API (based on index) to DB (based on id) solves https://issues.redhat.com/browse/AA-987
TODO: 
Before:
After:
Error:

Preserve ROI report params in DB

---

src/Containers/Reports/Layouts/Standard/ReportCard.tsx

This is more of a monkey patch and proper investigation how the error happend should be done
Go to Reports -> select `Hosts changed by job template` -> change visibility of any item in legend
Before:
`chrome-root.5d08171132d65412fc00.js:2 Error: Minified React error #130; visit http://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`
After:

Add missing chartType if not defined in params

---

src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx

RBAC can return {write:true} or {all:true}. In both case inputs are enabled in ROI report

Fix RBAC check

---

src/Containers/Reports/Layouts/AutomationCalculator/TemplatesTable/Row.tsx

Make rounding of values in the table same as in the chart

---

src/Components/Toolbar/DownloadPdfButton.tsx

This should fix an issue with BOP not being able to send emails to some email ids that have username associated with them with different email id as username value.

Changed email recipient to use username instead of email

---

src/Api/types.ts
src/Components/Toolbar/DownloadPdfButton.tsx
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx

Fixes https://issues.redhat.com/browse/AA-1038
Depends on https://gitlab.cee.redhat.com/automation-analytics/pdf-generator/-/merge_requests/83
Steps to reproduce:
* Change the followings: Automation/Manual cost, Manual time and Visibility to different value from default
* Click download button
* see the PDF
Before: 
Automation/Manual cost was hardcoded to 20/50 Manual time was hardcoded to 60 minutes Visibility of all items was hardcoded to true
After: 
Automation/Manual cost, Manual time and Visibility of all items is same as in the UI

[AA-1038] Add automationCost and manualCost to PDF button

---

src/Components/ApiStatus/LoadingState.tsx
src/Components/ApiStatus/NoData.tsx
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
src/Containers/Reports/Layouts/Standard/ReportCard.tsx
src/Containers/Reports/List/List.tsx
src/Containers/Reports/Shared/schemas/hostsByOrganizations.ts
src/Containers/Reports/Shared/schemas/jobsTasksByOrganization.ts

Condensed and standardized the height of the preview pane for all reports. 
Jira issue: https://issues.redhat.com/browse/AA-1075
Before: 
After:

[AA-1075] Report preview UX fixes

---

config/ansible-navigation.json
config/dev.webpack.config.js
profiles/local-frontend-and-api.js
profiles/local-frontend.js

- Move our apps in a collapsible “Automation Analytics” section
- changed our urls from ansible/insights/ to ansible/automation-analytics
https://issues.redhat.com/browse/AA-1114
@ryelo @Hyperkid123 this is a PR for standalone environment to go with cloud services PR https://github.com/RedHatInsights/cloud-services-config/pull/1097
For some reason the link does not work for me locally at the moment http://localhost:1337/beta/ansible/automation-analytics/reports/ can you help me figure out what is missing in my PR.

Side nav changes

---

src/Api/types.ts
src/Components/Toolbar/DownloadButton/Steps/EmailDetails/index.test.js
src/Components/Toolbar/DownloadButton/Steps/EmailDetails/index.tsx
src/Components/Toolbar/DownloadButton/Steps/PdfDetails/PdfDownload.tsx
src/Components/Toolbar/DownloadButton/Steps/PdfDetails/index.test.js
src/Components/Toolbar/DownloadButton/Steps/PdfDetails/index.tsx
src/Components/Toolbar/DownloadButton/index.test.js
src/Components/Toolbar/DownloadButton/index.tsx
src/Components/Toolbar/types.ts
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
src/Containers/Reports/Layouts/Standard/ReportCard.tsx

Fixed calculation for what to display as radio options on the export wizard when there are more than 100 items
Depends on: https://gitlab.cee.redhat.com/automation-analytics/pdf-generator/-/merge_requests/98

Export wizard fix

---

src/Components/Toolbar/DownloadButton/Steps/EmailDetails/index.test.js
src/Components/Toolbar/DownloadButton/Steps/EmailDetails/index.tsx
src/Components/Toolbar/DownloadButton/index.tsx

- Made changes to hide expiry date field when external users are not provided
- Added a note below expiry date field to specify that the expiry only applies to external users only
https://issues.redhat.com/browse/AA-1145
5
/cc @trahman73 @appuk

Made changes to hide expiry date field

---

src/Containers/Reports/List/List.tsx
src/Containers/Reports/List/ListItem/index.tsx

Bug fix- Report page filters remain active while different reports are previewed.
Jira issue: https://issues.redhat.com/browse/AA-1186

[AA-1186] Report list filters/preview card fix

---

src/Components/Toolbar/DownloadButton/index.tsx
src/Components/Toolbar/Groups/SortByGroup.tsx
src/Components/Toolbar/Groups/ToolbarInput/Select.tsx
src/Components/Toolbar/Groups/ToolbarInput/index.tsx
src/Components/Toolbar/Toolbar.tsx
src/Containers/Reports/Layouts/Standard/ReportCard.tsx
src/Containers/SavingsPlanner/List/List.js

All items should have an unique `data-cy` so Cypress can click on all of them using `daata-cy`. 
Only problem is pagination. It's a PF component and I'm only able to add `data-cy` to a whole thing not the buttons.
cc @fullsushidev

Add data-cy to toolbar items

---

src/Components/ApiStatus/ApiStatusWrapper.tsx
src/Components/EmptyList.tsx
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.test.js
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx

Requirements: when Automation Calculator report has a filter with no results it's possible to work with it like switching off a filter.
Partly fixes https://issues.redhat.com/browse/AA-1014
Before:
After (updated):

Fix empty state in ROI report

---

src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.test.js
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
src/Containers/Reports/Layouts/AutomationCalculator/TemplatesTable/Row.tsx
src/Containers/Reports/Layouts/AutomationCalculator/TemplatesTable/types.ts
src/Containers/Reports/Layouts/AutomationCalculator/TotalSavings.tsx

Fixes https://issues.redhat.com/browse/AA-1014
Fixes :
- The Total Savings figure in big green font reflects savings only for that page. Total Savings is always supposed to show the savings across all templates, as in, all pages. Lets have 2 displays here in order to make things very clear for the user to understand and to comply with the older version of the Automation Calculator screen where we ALWAYS displayed the overall total: 
Grand Total : This will display the entire total of the Savings across ALL pages 
Page Total : This will be a summation of all the Savings on the templates on the given page
- Individual page totals are not showing accurate numbers.  Note the page total number on page1. Now navigate to page2 and come back to page1. You will see a different total than what was …

Add current page and total Savings to ROI

---

cypress.json
cypress/support/commands.js
package-lock.json
package.json

- Bump cypress to v9.7 (since v10 has breaking changes)
- Bump and installs plugins
Previously, all tests were failing and now it's fixed with:
- Update login page ids
- Include command to accept the cookies

Update cypress tests to work on stage

---

src/Routes.tsx

The root route used the default route which is a not found
404 error screen. To make the user experience pleasant lets
redirect this route to the clusters page.

Fix: Add a redirect for the root route to the Routes

---

src/Components/Chart/index.tsx

Introduced by me in https://github.com/RedHatInsights/tower-analytics-frontend/pull/778
Steps to reproduce:
- go to Savings Planner
- click on any plan
- click Statistics tab
Before:
`Cannot read properties of undefined (reading 'toString')`
After:

When series has no id it's never hidden

---

pr_check.sh

This fixes
- gets the latest AA-backend image tag.  Previously this was using qa, but the image pull policy is "pull if not present", so the image was in some cases 2 months old on the server.
- "set +x" prevents the script from failing on command error
- dev-prod renamed keycloack route to keycloack-mocks.   this is also fixed

Existing pipeline fixes.

---

src/Containers/Reports/Layouts/Standard/ReportCard.tsx
src/Containers/Reports/Layouts/Standard/Table/index.tsx
src/Containers/Reports/Layouts/types.ts
src/QueryParams/useQueryParams.js

Added a kebab dropdown to the host anomaly run rate report which can be used to display all host rows, display only anomalous hosts, or display only non-anomalous hosts.
Depends on: https://gitlab.cee.redhat.com/automation-analytics/automation-analytics-backend/-/merge_requests/480
Jira ticket: https://issues.redhat.com/browse/AA-1256 
Before: ![Screen Shot 2022-08-01 at 3 46 44 PM](https://user-images.githubusercontent.com/89094075/182232726-9b297c14-9bba-420e-8b55-c5f599b61724.png)
After: ![Screen Shot 2022-08-01 at 3 31 31 PM](https://user-images.githubusercontent.com/89094075/182232727-4c520a95-cc28-4bd8-a3ef-f7619214f0bb.png)

[AA-1256] Anomalous hosts kebab dropdown

---

src/Containers/Reports/List/List.tsx

Fixes https://issues.redhat.com/browse/AA-1298
Steps to reproduce:
- login to stage
- go to 'reports' page
- go to any report page (host_anomalies_bar, hosts_by_organization, job_template_run_rate, module_usage_by_organization)
- click on 'reports' page to go back
- from time to time the page will not load correctly (it may take few tries to reproduce the bug)
Before:
console log
```console
vendors-node_modules…21c725b975.js:25241  action @@chrome/load-navigation-segment @ 14:55:02.179
vendors-node_modules…21c725b975.js:25241  prev state 
{chrome: {…}, globalFilter: {…}}
vendors-node_modules…21c725b975.js:25241  action     
{type: '@@chrome/load-navigation-segment', payload: {…}}
vendors-node_modules…21c725b975.js:25241  next state 
{chrome: {…}, globalFilter: {…}} …
```

Set selected report to default if null

---

cypress/support/e2e.js
cypress/support/login.js

Seems to be a leftover from another branch.
Fixes:
```log
Oops...we found an error preparing this test file:
> cypress/support/e2e.js
The error was:
Error: Webpack Compilation Error
./cypress/support/e2e.js
Module not found: Error: Can't resolve './pagination' in '/tmp/frontend/cypress/support'
```

Remove non-existant pagination import

---

cypress/e2e/JobExplorer.spec.js
cypress/support/commands.js
cypress/support/e2e.js
cypress/support/pagination.js

**The current implementation is a simpler version of PR #849 plan** in a slightly generic way.
On this PR, the Job explorer will be used as a model to develop the way we will test pagination for all the reports who basically needs to:
-- 
Depends on #848

Cypress pagination tests

---

cypress/e2e/Reports.spec.js
cypress/e2e/reports/AA2Migration.spec.js
cypress/e2e/reports/ChangesMadeByJobTemplate.spec.js
cypress/e2e/reports/HostAnomaliesBar.spec.js
cypress/e2e/reports/HostsByOrganization.spec.js
cypress/e2e/reports/HostsChangedByJobTemplate.spec.js
cypress/e2e/reports/JobTemplateRunRate.spec.js
cypress/e2e/reports/JobsTasksByOrganization.spec.js
cypress/e2e/reports/ModuleUsageByJobTemplate.spec.js
cypress/e2e/reports/ModuleUsageByOrganization.spec.js
cypress/e2e/reports/ModuleUsageByTask.spec.js
cypress/e2e/reports/MostUsedModules.spec.js
cypress/e2e/reports/TemplatesExplorer.spec.js
cypress/support/constants.js
cypress/support/login.js

This PR splits reports tests into single files for better readability and maintainability.
No code changes. Only renamed `cy.get['data-cy=....` to use the helper command `cy.getByCy(...`
To run only the tests from reports folder do:
`npx cypress run --spec 'cypress/e2e/reports/**/*'`
depends on #838

[Cypress] Refactor: Reports tests

---

README.md
cypress/e2e/JobExplorer.spec.js
cypress/e2e/reports/AA2Migration.spec.js
cypress/e2e/reports/ChangesMadeByJobTemplate.spec.js
cypress/e2e/reports/HostsByOrganization.spec.js
cypress/e2e/reports/HostsChangedByJobTemplate.spec.js
cypress/e2e/reports/JobTemplateRunRate.spec.js
cypress/e2e/reports/JobsTasksByOrganization.spec.js
cypress/e2e/reports/ModuleUsageByJobTemplate.spec.js
cypress/e2e/reports/ModuleUsageByOrganization.spec.js
cypress/e2e/reports/ModuleUsageByTask.spec.js
cypress/e2e/reports/MostUsedModules.spec.js
cypress/e2e/reports/TemplatesExplorer.spec.js
cypress/fixtures/example.json
cypress/fixtures/tables_pagination.json
cypress/support/commands.js
cypress/support/login.js
cypress/support/pagination.js
pr_check.sh

This PR updates the pagination tests (https://github.com/RedHatInsights/tower-analytics-frontend/pull/845) to work for all pages.
--
TLDR: Since the data-cy wasn't possible to be added to every single component to be tested, a bigger solution is needed, and to make the test more clean, several helper commands were created to be reused among the reports pages and any other page that uses the same pagination component and tables.
--
The final idea is to develop the following plan:
- Get the amount of pages available;
- Iterate and compare the amount of pages and how many times the pagination arrow can be clicked;
- Return the page's dropdown;
- Validate all existing values on the dropdown;
- Test clicking on each option and assert if the table is correctly updated;
- A next step would be to …

Extend cypress pagination tests

---

src/Api/api.ts
src/QueryParams/__tests__/useQueryParams.test.js
src/QueryParams/useQueryParams.js

Fixed pagination so that it resets when an item is selected from the kebab dropdown in the "Host runs in a job template" report. It now goes back to page 1 and the total items displayed in the pagination component is updated to reflect the total items that match the selected criteria. 
FYI- the fix for the same issue in "Automation calculator" was required in backend 
https://gitlab.cee.redhat.com/automation-analytics/automation-analytics-backend/-/merge_requests/554
Jira issue: https://issues.redhat.com/browse/AA-1377

[AA-1377] Reset pagination

---

src/Containers/Reports/Layouts/Standard/ReportCard.tsx

On the Host runs in a job template report: When a selection is made in the kebab dropdown and there are no matching results, the table headers remain on the page allowing you to use the kebab dropdown again to restore the page to its original state.
Jira issue: https://issues.redhat.com/browse/AA-1390
Before: <img width="1133" alt="Screen Shot 2022-10-17 at 3 46 12 PM" src="https://user-images.githubusercontent.com/89094075/196268596-d01d1fcc-80d4-43c7-bf40-cebb90acff50.png">
After: <img width="1132" alt="Screen Shot 2022-10-17 at 3 45 37 PM" src="https://user-images.githubusercontent.com/89094075/196268667-ede16bea-f4a4-40d9-8d20-cf606de563f4.png">

[AA-1390] Always show table headers with kebab dropdown

---

src/Containers/SavingsPlanner/List/ListItem/index.js

This PR addresses a bug in the savings planner that caused the page to break when there were multiple job statuses reported for one template. The UI can now handle a scenario where the API could send multiple statuses and as a result, a separate tag will appear for each status. 
A tooltip was also added to the "Last job status" label in order to display the date of the last reported status. 
Jira issue: https://issues.redhat.com/browse/AA-1412

[AA-1412] Display multiple job statuses

---

src/Components/JobStatus.tsx
src/Components/__snapshots__/JobStatus.test.js.snap
src/Containers/SavingsPlanner/Details/DetailsTab/index.js
src/Containers/SavingsPlanner/List/ListItem/index.js

Follow up to https://github.com/RedHatInsights/tower-analytics-frontend/pull/873 - addressing the same issue on the details tab in savings planner.
Jira issue: https://issues.redhat.com/browse/AA-1412

[AA-1412] Display multiple job statuses in details tab

---

src/Api/api.ts
src/Containers/Reports/Layouts/Standard/ReportCard.tsx

This PR additionally needs changes to schema to be able to draw axis and tick values properly. This PR replaces https://github.com/RedHatInsights/tower-analytics-frontend/pull/867
Dependent on https://gitlab.cee.redhat.com/automation-analytics/automation-analytics-backend/-/merge_requests/568
before
after

Adjusted code to hide extra scatter points

---

src/Containers/Reports/Layouts/Standard/ReportCard.tsx

When a specific bar is clicked in the host anomaly bar chart, ALL filters are carried to the host anomaly scatterplot report. Previously, only template and date range were being carried. 
Jira issue: https://issues.redhat.com/browse/AA-1323 
Before: 
After:

[AA-1323] Carry all filters to host anomaly scatterplot

---

src/Containers/Clusters/Clusters.js
src/Containers/Notifications/Notifications.tsx
src/Containers/OrganizationStatistics/OrganizationStatistics.js
src/Containers/OrganizationStatistics/OrganizationStatistics.test.js
src/Containers/Reports/List/List.tsx
src/Containers/SavingsPlanner/List/List.js

This PR fixes errors that a customer was seeing on many of the analytics pages when they have no data. Below is a list of pages that were fixed and the expected behavior:
- Organization statistics: Page will now display "No data" error component in any area (organizations, jobs, tasks) that is missing data
Before:
After:
- Clusters: Page will now display "No data" error component if there is missing data
Before: 
After: 
- Reports: Page will now display "No data" component if there is missing reports data
Before: 
After: 
- Savings planner: Page will now display "No data" error component if there is missing data
Before:
After: 
- Notifications: Page will now display "No data" component if there is missing data
Before:
After: 
***FYI: Automation calculator and job explorer pages were …

No data errors fix

---

src/App.js

Added an inline banner to the top of all automation analytics pages to alert customers of processing delays. The banner reads: "Automation Analytics is experiencing performance issues. Displayed data will be delayed. We apologize for the inconvenience."
Jira issue: https://issues.redhat.com/browse/AA-1472 
Before: 
After:
cc @fullsushidev

[AA-1472] crc alert banner for processing delays

---

config/dev.webpack.config.js

We are consuming left nav bar from https://github.com/RedHatInsights/insights-chrome/blob/ef63c8596285ab60ee2b769de2206e79662b78eb/src/components/Navigation/index.tsx
It uses https://github.com/RedHatInsights/insights-chrome/blob/master/src/utils/useNavigation.ts
After https://github.com/RedHatInsights/insights-chrome/pull/2157 it waits for Unleash to respond before it request navigation.json for the navigation component. In standalone mode we never get response from Unleash so we need to mock it to make it work.
When switching between branches with and without the fix you need to restart the UI because the change is in the webpack.
Before:
After:
Thanks @himdel and @MilanPospisil for debugging with me :)

Fix left nav bar in standalone mode

---

src/Components/ApiStatus/ApiStatusWrapper.test.js
src/Components/ApiStatus/ApiStatusWrapper.tsx
src/Components/ApiStatus/NoData.test.js
src/Components/ApiStatus/NoData.tsx

The `NoData` component has been updated to display a more user-friendly message in the "Host runs in a job template" report. Previously when a user clicked on the report, a simple "No data" message was displayed. Now, the message instructs the user on how to see data in the report. 
Jira issue: https://issues.redhat.com/browse/AA-1501
Before: 
After:

No data message update

---

src/Containers/Reports/List/List.tsx
src/Containers/Reports/List/ListItem/index.tsx
src/QueryParams/Provider.tsx
src/QueryParams/types.ts
src/QueryParams/useQueryParams.js

**PR content:**
- removes all logic that changes URL params directly
- allows update function to take `removeDefault` params that says that all params in namespace default should be removed
**Problem:**
Before we allowed unlimited number of API calls so we could make changes to URL multiple times per one user action. Now we have limited the number of API calls so if we do multiple changes to URL per one user action only one of those changes will be processed and rest will be discarded. For the Reports page when a report is selected for preview it updates `selected_report` param and removed all default params. Only the second one was done. This PR does those two changes at once.
**Steps to reproduce:**
- Go to Reports page
- Try to select different report
**Before:**
First report is …

Fix reports preview not changing reports

---

src/Containers/Reports/List/ListItem/index.tsx

This change adds tooltips to clarify action upon clicking on report tile.
Jira issue: [https://issues.redhat.com/browse/AA-1523](https://issues.redhat.com/browse/AA-1523)

Add tooltips for report tiles to clarify action upon clicking on title vs description of report tiles.

---

src/Containers/JobExplorer/JobExplorerListRow.js

Jira issue: [https://issues.redhat.com/browse/AA-1528](https://issues.redhat.com/browse/AA-1528)
This PR edits the external job links in the job explorer page to open in a new tab.
Links in page below now open in new tab.

[AA-1528] open external job links in new tab

---

src/Utilities/asyncComponent.js

Jira issue: https://issues.redhat.com/browse/AA-185
This PR replaces the "Loading..." text with a spinner when loading components.
Before:
https://user-images.githubusercontent.com/14355897/214971027-04714a95-cafa-4386-9045-a4775561ad8e.mov
After:
https://user-images.githubusercontent.com/14355897/214970622-dfbbff9f-e87c-45d1-90f1-d1798d128fe7.mov

Aa185 update async component loading screen

---

package-lock.json
package.json

Update @redhat-cloud-services/frontend-components-config-utilities to one with fixed issue with openid and nameandterms scopes
Relevant change https://github.com/RedHatInsights/frontend-components/pull/1714
Before:
Neverending looping
After:
Works correctly

Fix issue with missing scopes opeid and nameandterms

---

.gitignore
cypress/e2e/Clusters.spec.js
cypress/e2e/ReportsPage.spec.js
cypress/e2e/reports/TemplatesExplorer.spec.js
cypress/support/commands.js
cypress/support/constants.js
cypress/support/login.js
cypress/support/pagination.js
package-lock.json
package.json
pr_check.sh

This PR fixes the remaining tests to enable our auto promotion

fix to Cypress test

---

src/Utilities/helpers.test.js
src/Utilities/helpers.ts

Jira issue: https://issues.redhat.com/browse/AA-1649
Issue with custom date range error seems to be caused by formatDate only taking Date objects, while some .js files pass strings to the function. This fix changes the function to take in a Date object or a string, and expands the test to also check that Date objects are formatted correctly.

[AA-1649] custom date range selection fix

---

src/Utilities/helpers.ts

Adds console information to formatDate so we can compare info locally vs stage and production.

[AA-1649] add console.log to formatDate to output information for debugging

---

src/Containers/Reports/Layouts/AutomationCalculator/TemplatesTable/Row.tsx

Jira issue: https://issues.redhat.com/browse/AA-1557
This PR changes the behavior of the Manual Time textInput field to wait until the user clicks away from the field before resetting an empty value or 0 back to the default value of 60. This allows the user to clear the field and enter a new value. It also checks the value when changed, and only makes a call to the API if the value is greater than 0 or empty.
Before:
https://user-images.githubusercontent.com/14355897/229197811-511af8fe-5f84-425a-924a-45b882b34cdb.mov
After:
https://user-images.githubusercontent.com/14355897/229197463-aeb2ff3d-24fd-4450-99fc-e37f38070e9d.mov

[AA-1557] fix unable to save changes to manual time

---

src/Components/Toolbar/Groups/FiltersCategoriesGroup.tsx
src/Containers/Reports/List/List.tsx

This PR addresses a bug in the "Host runs in a job template" report where if there is no data for a selected date range, the template dropdown in the toolbar got corrupted. 
Jira issue: https://issues.redhat.com/browse/AA-1502 
There was an additional change made in the reports list view to address the broken redirect upon clicking the "clear all filters" button in the empty state (no jira issue).
Before (template dropdown):
After (template dropdown):
Before (clear filters redirect):
After (clear filters redirect):

Filtering fixes

---

src/Containers/OrganizationStatistics/OrganizationStatistics.test.js

Unmount wrapper to prevent error: `TypeError: Cannot read property '_location' of null`. This happens irreguleraly. 
cc: @fullsushidev

Fix Jest test in GH action

---

src/Containers/Reports/Layouts/Standard/Table/TableRow.tsx

When navigating from templates by organization to templates explorer by clicking on the numbers in the table, the templates explorer report will now be filtered by the organization id rather than by a list of templates. Any additional filters that were applied in the templates by organization report will also be carried over to templates explorer, if the filter option exists there. 
Jira issue: https://issues.redhat.com/browse/AA-1732
Before: 
After:

[AA-1732] Templates by org clickable linking fix

---

src/Containers/SavingsPlanner/Details/Details.test.js

in SavingsPlanner/Details
Disable for now to unblock others.

Fix TypeError: Cannot read properties of null (reading '_location') 

---

src/Routes.tsx

Fixes https://issues.redhat.com/browse/AA-1806
How to reproduce:
Try to reach the URL `/ansible/automation-analytics` or `/ansible/automation-analytics/`
Before:
It redirects to `/clusters`
After:
It redirects to `/ansible/automation-analytics/clusters`
@daphnemaeve please have a look. Thanks :)

Add missing prefix path when redirecting from path empty path

---

cypress/e2e/AutomationCalculator.spec.js
cypress/e2e/Clusters.spec.js
cypress/e2e/Dashboard.spec.js
cypress/e2e/Global.spec.js
cypress/e2e/JobExplorer.spec.js
cypress/e2e/Notifications.spec.js
cypress/e2e/OrganizationStatistics.spec.js
cypress/e2e/Reports.spec.js
cypress/e2e/ReportsPage.spec.js
cypress/e2e/SavingsPlanner.spec.js
cypress/e2e/reports/AA2Migration.spec.js
cypress/e2e/reports/HostsByOrganization.spec.js
cypress/fixtures/0/tables_pagination.json
cypress/fixtures/1/tables_pagination.json
cypress/fixtures/keycloakLoginFields.json
cypress/plugins/index.js
cypress/support/commands.js
cypress/support/constants.js
cypress/support/e2e.js
cypress/support/login.js
cypress/support/pagination.js
package-lock.json
package.json
pr_check.sh

<br>
Currently, we have some flaky tests on pr_checks and some other when running locally.
This PR attempts to solve most of the login issues between environments by:
- Wrapping the login into a session to keep for all the specs and including a validation to re-login when the session expired, speeding up the tests in approx. ~60%.
- Cleaning the code by moving the login strategy values into a fixture, simplifying redundant commands and deleting duplicated code.
<br>
Expect 5 specs (~ 7 tests) failing that will be fixed in a separate PR
<br>
depends on [AA backend MR-771](https://gitlab.cee.redhat.com/automation-analytics/automation-analytics-backend/-/merge_requests/771)
related to [AA-1723](https://issues.redhat.com/browse/AA-1723), [AA-1721](https://issues.redhat.com/browse/AA-1721)

Cypress login refactoring

---

.travis.yml
package-lock.json

TLDR: small change to workaround npm versions with travis.
Just like in #986, this PR attempts to fix travis build errors.
The latest one being the npm v9 that doesn't accept deprecated commands.
When trying to downgrade to npm v8 the build fails because of the node installation step.
After some research, I've removed node version from the travis file in favor of the .nvmrc
This fixed the issue for now, but we might want to revisit and rework this pipeline.

Fix broken pipeline from PR 988

---

src/Components/ApiStatus/AuthorizationErrorPage.tsx

When there is no data found in the Automation Analytics page in the Hybrid Cloud Console, it prompts users to enable Automation Analytics with a documentation url attached. 
https://docs.ansible.com/ansible-tower/latest/html/administration/usability_data_collection.html#automation-analytics
The above url, however, points to Ansible Tower 3.8.6 version, which is not the latest version of AAP.
This PR updates this url to the following latest url.
https://docs.ansible.com/automation-controller/latest/html/administration/usability_data_collection.html#automation-analytics

Update the Automation Analytics documentation url to the latest version

---

src/QueryParams/Provider.tsx

Before: Go to any screen with filters .. filters work; click clear all filters, twice (or once with default filters); filters don't work.
Now: filters keep working after resetting filters regardless
Looks like the problem was that when `namespace == DEFAULT_NAMESPACE` (which is the default state),
resetting it to `newQueryParams` would never happen, because right after that it would be overwritten by `{}` thanks to `removeDefault`. IIUC `removeDefault` should remove the default completely only when not replacing it with a new default, and it seems to work :)

Filter: clicking clear all filters when using default filters breaks filters

---

package.json

(v1.6.0 tag already exists)
mostly because crc mounts the app under a
div id="automation-analytics-application" version="1.1.0"
so we'll know the update happened :)

package.json: bump version to 1.7.0

---

src/Components/Toolbar/Toolbar.tsx
src/Containers/Reports/Layouts/AutomationCalculator/AutomationCalculator.tsx
src/Containers/Reports/Layouts/Standard/ReportCard.tsx

Fixes https://issues.redhat.com/browse/AAP-33165
introduced while doing another automation calculator fix in #1045, the download button & pagination was accidentally hidden in Automation Calculator
restoring and adjusting types to match
Before:
After:

Automation calculator: fix missing download button

---

.github/dependabot.yml

PF6 came out, crc doesn't support it yet,
stopping dependabot from offering that update.
(Also https://github.com/RedHatInsights/ansible-platform-dashboard/pull/159, https://github.com/ansible/ansible-hub-ui/pull/5305)
(Closes #1092)

dependabot: ignore patternfly 6
